
<?php $__env->startSection('title', 'Roles & Permissions'); ?>
<?php $__env->startSection('content'); ?>
<div class="roles-page">
    <header class="roles-header"><div><span>Administration</span><h1>Roles & Permissions</h1><p>Control which dashboard areas each administrator can access.</p></div><a href="<?php echo e(route('admin.admin-users.index')); ?>"><i class="fa-solid fa-users-gear"></i> Admin Team</a></header>
    <?php if(session('success')): ?><div class="roles-alert success"><?php echo e(session('success')); ?></div><?php endif; ?>
    <?php if(session('error')): ?><div class="roles-alert error"><?php echo e(session('error')); ?></div><?php endif; ?>
    <?php if($errors->any()): ?><div class="roles-alert error"><strong>Please correct these fields:</strong><ul><?php $__currentLoopData = $errors->all(); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $error): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><li><?php echo e($error); ?></li><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></ul></div><?php endif; ?>

    <section class="roles-panel">
        <div class="roles-heading"><span><i class="fa-solid fa-plus"></i></span><div><h2>Create custom role</h2><p>Select at least one permission.</p></div></div>
        <form method="POST" action="<?php echo e(route('admin.admin-roles.store')); ?>" class="role-form"><?php echo csrf_field(); ?>
            <div class="role-basics"><div class="field"><label>Role name</label><input name="name" value="<?php echo e(old('name')); ?>" maxlength="100" required></div><div class="field"><label>Description</label><input name="description" value="<?php echo e(old('description')); ?>" maxlength="2000"></div></div>
            <div class="permissions"><?php $__currentLoopData = $permissions; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $group=>$groupPermissions): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><fieldset><legend><?php echo e($group); ?></legend><?php $__currentLoopData = $groupPermissions; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $permission): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><label><input type="checkbox" name="permission_ids[]" value="<?php echo e($permission->id); ?>" <?php if(in_array((string)$permission->id,array_map('strval',old('permission_ids',[])),true)): echo 'checked'; endif; ?>><span><strong><?php echo e($permission->name); ?></strong><small><?php echo e($permission->slug); ?></small></span></label><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></fieldset><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>
            <footer><button type="submit"><i class="fa-solid fa-plus"></i> Create Role</button></footer>
        </form>
    </section>

    <section class="roles-panel"><div class="roles-heading"><span><i class="fa-solid fa-user-shield"></i></span><div><h2>Existing roles</h2><p>System roles can be edited but cannot be deleted.</p></div></div>
        <div class="role-list"><?php $__currentLoopData = $roles; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $role): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><article class="role-card"><div class="role-card-header"><div><h3><?php echo e($role->name); ?> <?php if($role->is_system): ?><span>System</span><?php endif; ?></h3><p><?php echo e($role->description ?: 'No description'); ?></p></div><strong><?php echo e(number_format($role->users_count)); ?> users</strong></div>
            <div class="permission-tags"><?php $__currentLoopData = $role->permissions; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $permission): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><span><?php echo e($permission->name); ?></span><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>
            <details><summary><i class="fa-regular fa-pen-to-square"></i> Edit role</summary><form method="POST" action="<?php echo e(route('admin.admin-roles.update',$role)); ?>" class="role-form compact"><?php echo csrf_field(); ?> <?php echo method_field('PUT'); ?><div class="role-basics"><div class="field"><label>Name</label><input name="name" value="<?php echo e($role->name); ?>" required maxlength="100"></div><div class="field"><label>Description</label><input name="description" value="<?php echo e($role->description); ?>" maxlength="2000"></div></div><?php $rolePermissionIds=$role->permissions->pluck('id')->map(fn($id)=>(string)$id)->all(); ?><div class="permissions"><?php $__currentLoopData = $permissions; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $group=>$groupPermissions): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><fieldset><legend><?php echo e($group); ?></legend><?php $__currentLoopData = $groupPermissions; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $permission): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><label><input type="checkbox" name="permission_ids[]" value="<?php echo e($permission->id); ?>" <?php if(in_array((string)$permission->id,$rolePermissionIds,true)): echo 'checked'; endif; ?>><span><strong><?php echo e($permission->name); ?></strong><small><?php echo e($permission->slug); ?></small></span></label><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></fieldset><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div><footer><button type="submit"><i class="fa-solid fa-floppy-disk"></i> Save Role</button></footer></form></details>
            <?php if(!$role->is_system && $role->users_count===0): ?><form method="POST" action="<?php echo e(route('admin.admin-roles.destroy',$role)); ?>" class="delete-role" onsubmit="return confirm('Delete this role?');"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button type="submit"><i class="fa-regular fa-trash-can"></i> Delete Role</button></form><?php endif; ?>
        </article><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>
    </section>
</div>
<?php $__env->stopSection(); ?>
<?php $__env->startPush('page-styles'); ?>
<style>
.roles-page{display:grid;gap:20px;color:#172033}.roles-header{display:flex;align-items:center;justify-content:space-between;padding:27px;border-radius:20px;background:linear-gradient(135deg,#111827,#7c3aed);color:#fff}.roles-header span{color:#ddd6fe;font-size:11px;font-weight:850;letter-spacing:.14em;text-transform:uppercase}.roles-header h1{margin:6px 0 0}.roles-header p{margin:7px 0 0;color:#ede9fe}.roles-header a{padding:10px 13px;border-radius:9px;background:#fff;color:#6d28d9;text-decoration:none;font-weight:800}.roles-alert{padding:14px 17px;border-radius:12px}.roles-alert.success{background:#ecfdf5;color:#047857;border:1px solid #a7f3d0}.roles-alert.error{background:#fff1f2;color:#be123c;border:1px solid #fecdd3}.roles-panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:17px;background:#fff}.roles-heading{display:flex;align-items:center;gap:12px;padding:18px 20px;border-bottom:1px solid #e2e8f0}.roles-heading>span{display:grid;place-items:center;width:42px;height:42px;border-radius:11px;background:#ede9fe;color:#7c3aed}.roles-heading h2{margin:0;font-size:18px}.roles-heading p{margin:4px 0 0;color:#64748b;font-size:12px}.role-form{padding:20px}.role-form.compact{margin-top:12px;padding:15px;background:#f8fafc;border-radius:12px}.role-basics{display:grid;grid-template-columns:1fr 2fr;gap:14px}.field label{display:block;margin-bottom:6px;font-size:12px;font-weight:800}.field input{width:100%;box-sizing:border-box;border:1px solid #cbd5e1;border-radius:9px;padding:10px;font:inherit}.permissions{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:17px}.permissions fieldset{margin:0;padding:12px;border:1px solid #e2e8f0;border-radius:11px}.permissions legend{padding:0 6px;color:#6d28d9;font-size:11px;font-weight:850}.permissions label{display:flex;align-items:flex-start;gap:8px;padding:7px 4px}.permissions strong,.permissions small{display:block}.permissions small{margin-top:2px;color:#94a3b8;font-size:9px}.role-form footer{display:flex;justify-content:flex-end;margin-top:16px}.role-form footer button{border:0;border-radius:9px;padding:10px 14px;background:#7c3aed;color:#fff;font:inherit;font-weight:800}.role-list{display:grid;gap:14px;padding:17px}.role-card{padding:16px;border:1px solid #e2e8f0;border-radius:13px}.role-card-header{display:flex;justify-content:space-between;gap:15px}.role-card-header h3{margin:0}.role-card-header h3 span{padding:4px 7px;border-radius:999px;background:#ede9fe;color:#6d28d9;font-size:9px}.role-card-header p{margin:5px 0 0;color:#64748b}.permission-tags{display:flex;flex-wrap:wrap;gap:6px;margin-top:13px}.permission-tags span{padding:5px 8px;border-radius:999px;background:#f1f5f9;font-size:10px;font-weight:750}.role-card details{margin-top:14px}.role-card summary{color:#6d28d9;font-weight:800;cursor:pointer}.delete-role{margin-top:12px}.delete-role button{border:1px solid #fecdd3;border-radius:8px;padding:8px 11px;background:#fff1f2;color:#be123c;font-weight:800}
@media(max-width:950px){.permissions{grid-template-columns:repeat(2,1fr)}}@media(max-width:680px){.roles-header{align-items:stretch;flex-direction:column;gap:15px}.role-basics,.permissions{grid-template-columns:1fr}.role-card-header{flex-direction:column}.roles-header a{text-align:center}}
</style>
<?php $__env->stopPush(); ?>

<?php echo $__env->make('admin.layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\ArizonaOutfits\resources\views/admin/admin-roles/index.blade.php ENDPATH**/ ?>