<?php
require __DIR__.'/../customer-dashboard-files/_checks/bootstrap.php';
spl_autoload_register(function($class){if($class==='App\Http\Controllers\ShopController')require __DIR__.'/_staged/app/Http/Controllers/ShopController.php';},true,true);
app('view')->getFinder()->prependLocation(__DIR__.'/_staged/resources/views');
use App\Models\{Product,ProductCategory};
$parent=ProductCategory::create(['title'=>'Outerwear fixture','slug'=>'outerwear-fixture','description'=>'Fixture collection description','meta_title'=>'Outerwear collection title']);$child=ProductCategory::create(['title'=>'Jackets fixture','slug'=>'jackets-fixture','parent_id'=>$parent->id]);$grandchild=ProductCategory::create(['title'=>'Winter fixture','slug'=>'winter-fixture','parent_id'=>$child->id]);$other=ProductCategory::create(['title'=>'Other fixture','slug'=>'other-fixture']);
foreach([$parent,$child,$grandchild,$other]as $i=>$category){$p=Product::create(['title'=>'Category fixture '.$i,'slug'=>'category-fixture-'.$i,'status'=>'active','regular_price'=>10,'stock'=>5]);$p->categories()->attach($category->id);}
$hidden=Product::create(['title'=>'Hidden fixture','slug'=>'hidden-category-fixture','status'=>'draft','regular_price'=>10]);$hidden->categories()->attach($parent->id);
function categoryRequest(array $query=[]){$r=Illuminate\Http\Request::create('/product-category/outerwear-fixture','GET',$query);$r->setLaravelSession(app('session')->driver());app()->instance('request',$r);return $r;}
$controller=new App\Http\Controllers\ShopController;$view=$controller->category($parent->slug,categoryRequest());$data=$view->getData();if($view->name()!=='products.category'||$data['products']->total()!==3||$data['products']->perPage()!==15)throw new RuntimeException('Category scope/pagination mismatch');echo "PASS: category returns its own view, includes descendants, excludes unrelated/draft products, 15 per page.\n";
$html=$view->render();foreach(['Outerwear collection title','az-category-intro','Fixture collection description',route('products.category',$child->slug),'action="'.route('products.category',$parent->slug).'"']as $expected)if(!str_contains($html,$expected))throw new RuntimeException('Missing '.$expected);if(str_contains($html,'name="categories[]"'))throw new RuntimeException('Category can be switched by form');echo "PASS: category title, description, subcategory links and scoped form URLs render.\n";
$data=$controller->category($parent->slug,categoryRequest(['categories'=>[$other->slug],'search'=>'Category fixture 1']))->getData();if($data['products']->total()!==1 || $data['products']->first()->title!=='Category fixture 1')throw new RuntimeException('Scope bypass');echo "PASS: search works and category query cannot escape URL scope.\n";
try{$controller->category('missing-category',categoryRequest());throw new RuntimeException('Missing slug accepted');}catch(Illuminate\Database\Eloquent\ModelNotFoundException){echo "PASS: missing category returns not found.\n";}
$empty=ProductCategory::create(['title'=>'Empty fixture','slug'=>'empty-fixture']);$emptyHtml=$controller->category($empty->slug,categoryRequest())->render();if(!str_contains($emptyHtml,'No products found'))throw new RuntimeException('Empty state missing');echo "PASS: empty category renders normally.\n";
$shop=$controller->index(categoryRequest());if($shop->name()!=='products.index'||$shop->getData()['products']->total()!==4)throw new RuntimeException('Shop regression');if(str_contains($shop->render(),'az-category-intro">'))throw new RuntimeException('Category hero leaked to shop');echo "PASS: normal Shop remains independent.\n";
foreach(['index','category']as $name){$compiled=app('blade.compiler')->compileString(file_get_contents(__DIR__.'/_staged/resources/views/products/'.$name.'.blade.php'));file_put_contents(__DIR__.'/compiled-'.$name.'.php',$compiled);}