@extends('layouts.app')
@section('title', 'Order '.($order->order_number ?: '#'.$order->id))
@include('customer.partials.styles')
@section('content')
<section class="customer-account"><div class="account-shell">
<header class="account-heading"><div><small>Order details</small><h1>{{ $order->order_number ?: 'Order #'.$order->id }}</h1><p>Placed {{ $order->created_at?->format('d F Y \a\t g:i A') }}.</p></div><div class="order-actions"><a class="secondary" href="{{ route('customer.orders.invoice',$order->id) }}" target="_blank"><i class="fa-regular fa-eye"></i> View invoice</a><a href="{{ route('customer.orders.invoice.download',$order->id) }}"><i class="fa-solid fa-download"></i> Download PDF</a></div></header>
@include('customer.partials.navigation')
<div class="order-summary"><section class="account-panel"><header class="account-panel-heading"><h2>Items</h2><span class="account-status {{ $order->order_status }}">{{ str($order->order_status ?: 'pending')->headline() }}</span></header><div class="account-table-wrap"><table class="account-table"><thead><tr><th>Product</th><th>Quantity</th><th>Price</th><th>Total</th></tr></thead><tbody>
@foreach($order->items as $item) @php($itemName=$item->product_name ?? $item->name ?? $item->product?->name ?? 'Product') @php($itemPrice=(float)($item->unit_price ?? $item->price ?? 0)) @php($itemTotal=(float)($item->total ?? $item->subtotal ?? ($itemPrice*(int)$item->quantity)))
<tr><td><strong>{{ $itemName }}</strong>@if($item->variant)<small>{{ $item->variant->name ?? $item->variant->sku ?? 'Variant' }}</small>@endif</td><td>{{ number_format((int)$item->quantity) }}</td><td>{{ strtoupper($order->currency ?: 'USD') }} {{ number_format($itemPrice,2) }}</td><td>{{ strtoupper($order->currency ?: 'USD') }} {{ number_format($itemTotal,2) }}</td></tr>@endforeach
</tbody></table></div><div class="order-card"><div class="order-meta"><div><small>Subtotal</small><strong>{{ strtoupper($order->currency ?: 'USD') }} {{ number_format((float)$order->subtotal,2) }}</strong></div><div><small>Discount</small><strong>{{ strtoupper($order->currency ?: 'USD') }} {{ number_format((float)$order->discount,2) }}</strong></div><div><small>Shipping</small><strong>{{ strtoupper($order->currency ?: 'USD') }} {{ number_format((float)($order->shipping_price ?? $order->shipping),2) }}</strong></div><div><small>Order total</small><strong>{{ strtoupper($order->currency ?: 'USD') }} {{ number_format((float)$order->total,2) }}</strong></div></div></div></section>
<aside class="account-panel order-card"><h2>Delivery</h2><p class="order-address"><strong>{{ $order->shipping_name ?: $order->billing_name }}</strong><br>{{ $order->shipping_address ?: $order->billing_address }}<br>{{ $order->shipping_city ?: $order->billing_city }} {{ $order->shipping_state ?: $order->billing_state }} {{ $order->shipping_zip ?: $order->billing_zip }}<br>{{ $order->shipping_country ?: $order->billing_country }}</p><div class="order-meta"><div><small>Payment</small><strong>{{ str($order->payment_status ?: 'pending')->headline() }}</strong></div><div><small>Method</small><strong>{{ str($order->payment_method ?: 'Not available')->headline() }}</strong></div><div><small>Tracking</small><strong>{{ $order->tracking_number ?: 'Pending' }}</strong></div><div><small>Estimated delivery</small><strong>{{ $order->estimated_delivery ?: 'To be confirmed' }}</strong></div></div>@if($order->notes->isNotEmpty())<h3>Updates</h3>@foreach($order->notes as $note)<p class="order-address">{{ $note->note }}</p>@endforeach @endif</aside></div>
</div></section>
@endsection
