@extends('customer.layouts.app')
@section('title', 'Order '.($order->order_number ?: '#'.$order->id))
@section('page-heading', 'Order Details')
@section('content')
<header class="customer-page-heading"><div><span>Order details</span><h2>{{ $order->order_number ?: 'Order #'.$order->id }}</h2><p>Placed {{ $order->created_at?->format('d F Y \a\t g:i A') }}.</p></div><div class="customer-heading-actions"><a class="secondary" href="{{ route('customer.orders.invoice',$order->id) }}" target="_blank"><i class="fa-regular fa-eye"></i> View invoice</a><a href="{{ route('customer.orders.invoice.download',$order->id) }}"><i class="fa-solid fa-download"></i> Download PDF</a></div></header>
<div class="customer-order-grid">
<section class="customer-panel"><header class="customer-panel-heading"><div><span>Purchased products</span><h3>Order items</h3></div><span class="customer-status {{ $order->order_status }}">{{ str($order->order_status ?: 'pending')->headline() }}</span></header><div class="customer-table-wrap"><table class="customer-table"><thead><tr><th>Product</th><th>Quantity</th><th>Price</th><th>Total</th></tr></thead><tbody>
@foreach($order->items as $item) @php($itemName=$item->product_name ?? $item->name ?? $item->product?->name ?? 'Product') @php($itemPrice=(float)($item->unit_price ?? $item->price ?? 0)) @php($itemTotal=(float)($item->total ?? $item->subtotal ?? ($itemPrice*(int)$item->quantity)))
<tr><td><strong>{{ $itemName }}</strong>@if($item->variant)<small>{{ $item->variant->name ?? $item->variant->sku ?? 'Variant' }}</small>@endif</td><td>{{ number_format((int)$item->quantity) }}</td><td>{{ strtoupper($order->currency ?: 'USD') }} {{ number_format($itemPrice,2) }}</td><td><strong>{{ strtoupper($order->currency ?: 'USD') }} {{ number_format($itemTotal,2) }}</strong></td></tr>@endforeach
</tbody></table></div><div class="customer-totals"><div><small>Subtotal</small><strong>{{ strtoupper($order->currency ?: 'USD') }} {{ number_format((float)$order->subtotal,2) }}</strong></div><div><small>Discount</small><strong>{{ strtoupper($order->currency ?: 'USD') }} {{ number_format((float)$order->discount,2) }}</strong></div><div><small>Shipping</small><strong>{{ strtoupper($order->currency ?: 'USD') }} {{ number_format((float)($order->shipping_price ?? $order->shipping),2) }}</strong></div><div class="grand-total"><small>Order total</small><strong>{{ strtoupper($order->currency ?: 'USD') }} {{ number_format((float)$order->total,2) }}</strong></div></div></section>
<aside class="customer-panel customer-delivery-card"><header class="customer-panel-heading"><div><span>Shipment</span><h3>Delivery details</h3></div></header><div class="customer-address"><span class="customer-address-icon"><i class="fa-solid fa-location-dot"></i></span><p><strong>{{ $order->shipping_name ?: $order->billing_name }}</strong><br>{{ $order->shipping_address ?: $order->billing_address }}<br>{{ $order->shipping_city ?: $order->billing_city }} {{ $order->shipping_state ?: $order->billing_state }} {{ $order->shipping_zip ?: $order->billing_zip }}<br>{{ $order->shipping_country ?: $order->billing_country }}</p></div><dl class="customer-detail-list"><div><dt>Payment</dt><dd>{{ str($order->payment_status ?: 'pending')->headline() }}</dd></div><div><dt>Method</dt><dd>{{ str($order->payment_method ?: 'Not available')->headline() }}</dd></div><div><dt>Tracking</dt><dd>{{ $order->tracking_number ?: 'Pending' }}</dd></div><div><dt>Estimated delivery</dt><dd>{{ $order->estimated_delivery ?: 'To be confirmed' }}</dd></div></dl>@if($order->notes->isNotEmpty())<div class="customer-order-updates"><h4>Order updates</h4>@foreach($order->notes as $note)<p>{{ $note->note }}</p>@endforeach</div>@endif</aside>
</div>
@endsection
