<?php
require __DIR__.'/bootstrap.php';
use App\Models\{Product,ProductVariant,InventoryHistory,InventoryAlert,PurchaseOrder,PurchaseOrderItem,PurchaseOrderReceipt,SupplierReturn,SupplierProduct};
use Illuminate\Support\Facades\{Auth,Mail,Bus};
$alerts=new App\Services\InventoryAlertService;
$reports=new App\Http\Controllers\Admin\InventoryReportController;
$history=new App\Http\Controllers\Admin\InventoryHistoryController;
$valuation=new App\Http\Controllers\Admin\StockValuationController;
$reorder=new App\Http\Controllers\Admin\ReorderDashboardController;
$purchasing=new App\Http\Controllers\Admin\PurchaseOrderController;
$receiving=new App\Http\Controllers\Admin\PurchaseOrderReceivingController;
$suppliers=new App\Http\Controllers\Admin\SupplierController;
$drafts=new App\Http\Controllers\Admin\PurchaseOrderDraftController;
$simple=Product::create(['title'=>'Simple fixture','slug'=>'simple-fixture','sku'=>'SIMPLE','regular_price'=>100,'cost_price'=>10,'stock'=>2,'reorder_point'=>5,'status'=>'active']);
$variable=Product::create(['title'=>'Variable fixture','slug'=>'variable-fixture','sku'=>'PARENT','regular_price'=>100,'cost_price'=>10,'stock'=>100,'reorder_point'=>5,'status'=>'active']);
$v1=ProductVariant::create(['product_id'=>$variable->id,'sku'=>'VAR-1','regular_price'=>null,'sale_price'=>50,'stock'=>3,'reorder_point'=>5,'options'=>[['option_name'=>'Size','value_label'=>'Small']]]);
$v2=ProductVariant::create(['product_id'=>$variable->id,'sku'=>'VAR-2','regular_price'=>200,'stock'=>4,'reorder_point'=>5]);
$supplier=supplier();$foreignSupplier=supplier();
run('Inventory reports accounting',function()use($reports){$data=$reports->index(req())->getData();check('Inventory reports count simple plus variant units without parent double counting',$data['totalStockUnits']===9,'Expected 9; actual '.$data['totalStockUnits']);});
run('Stock valuation accounting',function()use($valuation){$data=$valuation->index(req())->getData();check('Valuation uses actual simple and variant units',$data['totalUnits']===9,'Expected 9; actual '.$data['totalUnits']);check('Valuation cost includes seven variant units and two simple units',(float)$data['totalCost']===90.0,'Expected 90; actual '.$data['totalCost']);});
run('Reorder inventory rows',function()use($reorder,$variable){$items=(new ReflectionMethod($reorder,'getReorderItems'))->invoke($reorder);check('Reorder lists variants without duplicating parent',$items->count()===3 && !$items->contains(fn($i)=>$i['product_id']===$variable->id && !$i['is_variant']));check('Reorder units agree with purchasable stock',$items->sum('stock')===9);});
$zero=Product::create(['title'=>'Zero sale','slug'=>'zero-sale','sku'=>'ZERO','regular_price'=>100,'sale_price'=>0,'cost_price'=>10,'stock'=>2,'status'=>'active']);
run('Zero sale valuation',function()use($valuation,$zero){$rows=(new ReflectionMethod($valuation,'getValuationProducts'))->invoke($valuation);$row=$rows->firstWhere('id',$zero->id);check('Valuation respects valid zero sale price',(float)$row->selling_price===0.0,'Model/cart price 0; valuation '.$row->selling_price);});
run('Alert creation and deduplication',function()use($alerts,$simple){$alerts->checkProduct($simple);$alerts->checkProduct($simple);check('One active low-stock alert after repeated checks',InventoryAlert::where('product_id',$simple->id)->where('status','active')->count()===1);check('Repeated alert does not resend notification',Mail::sent(App\Mail\InventoryAlertMail::class)->count()===1);$simple->update(['stock'=>0]);$alerts->checkProduct($simple);check('Out-of-stock transition resolves old low alert',InventoryAlert::where('product_id',$simple->id)->where('status','active')->where('alert_type','out_of_stock')->count()===1 && InventoryAlert::where('product_id',$simple->id)->where('alert_type','low_stock')->first()->status==='resolved');$simple->update(['stock'=>2]);$alerts->checkProduct($simple);});
$threshold=Product::create(['title'=>'Custom threshold','slug'=>'custom-threshold','regular_price'=>100,'cost_price'=>10,'stock'=>8,'reorder_point'=>10,'status'=>'active']);
run('Custom alert threshold',function()use($alerts,$threshold,$reorder,$reports){$alerts->checkProduct($threshold);$items=(new ReflectionMethod($reorder,'getReorderItems'))->invoke($reorder);check('Configured product threshold agrees with active alert',InventoryAlert::where('product_id',$threshold->id)->where('status','active')->exists(),'Stock 8 / reorder point 10 / global threshold 5: reorder needed='.$items->firstWhere('product_id',$threshold->id)['needs_reorder']);$data=$reports->index(req())->getData();check('Low-stock report respects product reorder point',$data['lowStockItems']->contains('id',$threshold->id));});
run('Reorder threshold boundary',function()use($reorder,$simple){$simple->update(['stock'=>5,'reorder_quantity'=>null]);$rows=(new ReflectionMethod($reorder,'getReorderItems'))->invoke($reorder);$row=$rows->firstWhere('product_id',$simple->id);check('Reorder-needed row recommends at least one unit',!$row['needs_reorder'] || $row['suggested_quantity']>0,'Stock equals threshold: needed='.($row['needs_reorder']?'yes':'no').'; suggested='.$row['suggested_quantity']);$simple->update(['stock'=>2]);});
run('Supplier creation actor',function()use($suppliers){try{$suppliers->store(req(['company_name'=>'Created by admin','currency'=>'GBP','status'=>'active']));check('Admin supplier creation uses valid admin ownership',true);}catch(Illuminate\Database\QueryException $e){check('Admin supplier creation uses valid admin ownership',false,'Admin ID 99 has no users row; '.$e->getPrevious()->getMessage());}});
run('Admin inventory adjustment',function()use($simple,$alerts,$admin){$service=new App\Services\InventoryAdjustmentService(new App\Services\InventoryHistoryService,$alerts);try{$service->adjustProduct($simple,'add',1,'Audit adjustment',null,$admin);check('Admin model accepted by inventory adjustment',true);}catch(TypeError $e){check('Admin model accepted by inventory adjustment',false,$e->getMessage());}});
$po=po($supplier);$poLine=line($po,$simple,5);$po->recalculateTotals();
run('Tracked receiving ownership',function()use($receiving,$po,$poLine,$simple){$before=$simple->fresh()->stock;try{$receiving->store(req(['items'=>[['purchase_order_item_id'=>$poLine->id,'quantity_received'=>1]]]),$po);check('Tracked receiving works for separate admin ID',true);}catch(Illuminate\Database\QueryException $e){check('Tracked receiving works for separate admin ID',false,'Receipt received_by references users; '.$e->getPrevious()->getMessage());check('Failed receipt rolls back stock and received quantity',$simple->fresh()->stock===$before && $poLine->fresh()->quantity_received===0);}});
run('Purchase order create and duplicate validation',function()use($purchasing,$supplier,$simple){
    $data=['supplier_id'=>$supplier->id,'order_date'=>now()->toDateString(),'items'=>[['identifier'=>'product:'.$simple->id,'quantity'=>2,'unit_cost'=>12],['identifier'=>'product:'.$simple->id,'quantity'=>2,'unit_cost'=>12]]];
    check('Purchase-order creation rejects duplicate item identifiers',validationBlocked(fn()=>$purchasing->store(req($data))));
    array_pop($data['items']);$purchasing->store(req($data));$created=PurchaseOrder::latest('id')->first();
    check('Purchase-order creator is admin not customer',$created->admin_id===99 && $created->created_by===null);
    $purchasing->markOrdered($created);check('Draft can transition to ordered',$created->fresh()->status==='ordered');
});
// Use an overlapping customer ID solely to exercise downstream logic after
// reproducing the separate-admin FK failure. This does not fix actor identity.
DB::table('users')->insert(['id'=>99,'name'=>'Unrelated customer sharing admin ID','email'=>'overlap@example.test']);
$po2=po($supplier);$line2=line($po2,$simple,4);
run('Tracked receipt processing',function()use($receiving,$po2,$line2,$simple){$before=$simple->fresh()->stock;$receiving->store(req(['items'=>[['purchase_order_item_id'=>$line2->id,'quantity_received'=>2]]]),$po2);check('Tracked receiving creates receipt rows and stock',$simple->fresh()->stock===$before+2 && PurchaseOrderReceipt::where('purchase_order_id',$po2->id)->count()===1);$receipt=PurchaseOrderReceipt::where('purchase_order_id',$po2->id)->first();check('Receipt receiver is the actual admin model',$receipt->receiver_actor instanceof App\Models\Admin,'Actual receiver model='.get_class($receipt->receiver_actor));$movement=InventoryHistory::where('metadata->purchase_order_id',$po2->id)->latest('id')->first();check('Tracked receipt history records admin_id',$movement && $movement->admin_id===99 && $movement->user_id===null,'Actual user_id='.$movement?->user_id.'; admin_id='.$movement?->admin_id);});
run('Receiving synchronizes alerts',function()use($receiving,$po2,$line2,$simple){$receiving->store(req(['items'=>[['purchase_order_item_id'=>$line2->id,'quantity_received'=>2]]]),$po2);check('Replenishment resolves active alert after stock exceeds threshold',!InventoryAlert::where('product_id',$simple->id)->where('status','active')->exists(),'Stock now '.$simple->fresh()->stock.'; threshold 5');check('Full receipt changes order to received',$po2->fresh()->status==='received');});
run('Receipt quantity and ownership guards',function()use($receiving,$po2,$line2,$poLine){check('Cannot over-receive remaining quantity',validationBlocked(fn()=>$receiving->store(req(['items'=>[['purchase_order_item_id'=>$line2->id,'quantity_received'=>99]]]),$po2)));check('Cannot receive item from another purchase order',validationBlocked(fn()=>$receiving->store(req(['items'=>[['purchase_order_item_id'=>$poLine->id,'quantity_received'=>1]]]),$po2)));$draft=po($po2->supplier,['status'=>'draft']);$line=line($draft,$line2->product,1);check('Draft receipt rejected',validationBlocked(fn()=>$receiving->store(req(['items'=>[['purchase_order_item_id'=>$line->id,'quantity_received'=>1]]]),$draft)));});
run('Receipt correction and returns',function()use($receiving,$po2,$line2,$simple){$receipt=PurchaseOrderReceipt::where('purchase_order_id',$po2->id)->first();$receiptItem=$receipt->items()->first();$before=$simple->fresh()->stock;$receiving->correct(req(['quantity'=>1,'reason'=>'Audit correction']),$po2,$receipt,$receiptItem);check('Correction reduces stock and received quantity',$simple->fresh()->stock===$before-1 && $line2->fresh()->quantity_received===3);check('Correction cannot exceed receipt quantity',validationBlocked(fn()=>$receiving->correct(req(['quantity'=>2,'reason'=>'Over correction']),$po2,$receipt,$receiptItem)));$before=$simple->fresh()->stock;$receiving->storeReturn(req(['reason_category'=>'damaged','reason'=>'Fixture damaged item','items'=>[['purchase_order_item_id'=>$line2->id,'quantity'=>1]]]),$po2);$return=SupplierReturn::where('purchase_order_id',$po2->id)->latest('id')->first();check('Supplier return reduces stock once',$simple->fresh()->stock===$before-1 && $return->status==='submitted');$receiving->cancelReturn(req(['cancellation_reason'=>'Fixture cancellation']),$po2,$return);check('Cancelling submitted return restores stock',$simple->fresh()->stock===$before);check('Repeated return cancellation is blocked',validationBlocked(fn()=>$receiving->cancelReturn(req(['cancellation_reason'=>'Repeat cancellation']),$po2,$return)));});
run('Stale purchase-order transitions',function()use($purchasing,$po2){$stale=PurchaseOrder::find($po2->id);$stale->forceFill(['status'=>'ordered']);$purchasing->markOrdered($stale);check('markOrdered does not downgrade received state with stale input',$po2->fresh()->status==='partially_received','Actual status='.$po2->fresh()->status);$staleDraft=PurchaseOrder::find($po2->id);$staleDraft->forceFill(['status'=>'draft']);$purchasing->markOrdered($staleDraft);check('markOrdered rechecks locked persisted status',$po2->fresh()->status==='partially_received','Actual status='.$po2->fresh()->status);});
run('Supplier deletion safeguards',function()use($suppliers,$supplier){$suppliers->destroy($supplier);check('Supplier with open purchase orders cannot be deleted',App\Models\Supplier::find($supplier->id)!==null);$unused=supplier();$suppliers->destroy($unused);check('Unreferenced supplier is soft deleted',App\Models\Supplier::onlyTrashed()->whereKey($unused->id)->exists());});
run('Archived customer-order history',function()use($simple,$history){$order=App\Models\Order::create(['user_id'=>1,'order_number'=>'ARCHIVED-AUDIT','payment_status'=>'paid']);$movement=InventoryHistory::create(['product_id'=>$simple->id,'order_id'=>$order->id,'admin_id'=>99,'quantity_change'=>-1,'stock_before'=>5,'stock_after'=>4,'movement_type'=>'order_deduction','reason'=>'Audit archived order']);$order->delete();check('History retains archived order relation',$movement->fresh()->order!==null);$list=$history->index(req(['search'=>'ARCHIVED-AUDIT']))->getData()['history'];check('History search finds archived order number',$list->contains('id',$movement->id));$list=$history->index(req(['search'=>'Fixture admin']))->getData()['history'];check('History can search current admin actor',$list->contains('id',$movement->id));});
run('Date filter validation',function()use($reports){try{$reports->index(req(['date_range'=>'custom','start_date'=>'not-a-date','end_date'=>'2026-10-01']));check('Reports reject malformed dates with validation',false,'Invalid date accepted');}catch(Illuminate\Validation\ValidationException){check('Reports reject malformed dates with validation',true);}catch(Carbon\Exceptions\InvalidFormatException $e){check('Reports reject malformed dates with validation',false,'Uncaught Carbon parse exception instead of validation');}});
// Current local rating/document tables lack the controller's newer columns.
run('Supplier rating schema',function()use($supplier){try{(new App\Http\Controllers\Admin\SupplierRatingController)->store(req(['quality_rating'=>4,'delivery_rating'=>4,'communication_rating'=>4,'pricing_rating'=>4]),$supplier);check('Supplier rating fields match local schema',true);}catch(Illuminate\Database\QueryException $e){check('Supplier rating fields match local schema',false,$e->getPrevious()->getMessage());}});
run('Supplier document schema',function()use($supplier){$r=req(['title'=>'Fixture contract','document_type'=>'contract','expires_at'=>now()->addDays(10)->toDateString()]);$r->files->set('document',Illuminate\Http\UploadedFile::fake()->create('contract.pdf',2,'application/pdf'));try{(new App\Http\Controllers\Admin\SupplierDocumentController)->store($r,$supplier);check('Supplier upload fields match local schema',true);}catch(Illuminate\Database\QueryException $e){check('Supplier upload fields match local schema',false,$e->getPrevious()->getMessage());check('Failed upload removes fixture file',count(Illuminate\Support\Facades\Storage::disk('public')->allFiles())===0);}});
run('Supplier document expiry alias',function()use($supplier){$document=$supplier->documents()->first();check('Document expiry alias exposes a date object for the view',$document->expires_at instanceof Carbon\CarbonInterface,'Alias value type='.get_debug_type($document->expires_at));});
// Full actual menu pages and related create/detail screens; no browser actions.
$pages=['Inventory Alerts'=>fn()=>(new App\Http\Controllers\Admin\InventoryAlertController)->index(req()),'Inventory History'=>fn()=>$history->index(req()),'Inventory Reports'=>fn()=>$reports->index(req()),'Stock Valuation'=>fn()=>$valuation->index(req()),'Reorder Dashboard'=>fn()=>$reorder->index(req()),'Purchase Orders'=>fn()=>$purchasing->index(req()),'Suppliers'=>fn()=>$suppliers->index(req()),'Purchase Order detail'=>fn()=>$purchasing->show($po2->fresh()),'Purchase Order create'=>fn()=>$purchasing->createFromReorder(req(['selected_items'=>['product:'.$simple->id]])),'Receiving and Returns'=>fn()=>$receiving->index($po2->fresh()),'Supplier detail'=>fn()=>$suppliers->show($supplier->fresh()),'Supplier create'=>fn()=>$suppliers->create(),'Supplier products'=>fn()=>(new App\Http\Controllers\Admin\SupplierProductController)->index(req(),$supplier)];
$render=[];foreach($pages as $name=>$factory){try{$html=$factory()->render();$render[$name]=['result'=>'PASS','bytes'=>strlen($html)];check('Page render: '.$name,strlen($html)>500);}catch(Throwable $e){$render[$name]=['result'=>'ERROR','exception'=>get_class($e),'detail'=>$e->getMessage()];check('Page render: '.$name,false,get_class($e).' '.$e->getMessage());}}
foreach(['admin.inventory-alerts.index','admin.inventory-history.index','admin.inventory-reports.index','admin.stock-valuation.index','admin.reorder-dashboard.index','admin.purchase-orders.index','admin.suppliers.index'] as $name){run('Permission check '.$name,function()use($name,$app){$mock=Mockery::mock(App\Models\Admin::class)->makePartial();$mock->shouldReceive('isActive')->andReturn(true);$mock->shouldReceive('hasAdminPermission')->andReturn(false);$app['auth']->guard('admin')->setUser($mock);$r=req();$r->setRouteResolver(fn()=>$app['router']->getRoutes()->getByName($name));try{$response=(new App\Http\Middleware\AdminMiddleware)->handle($r,fn()=>response('allowed'));check('Server denies admin without module permission: '.$name,false,'Actual response '.$response->getStatusCode());}catch(Symfony\Component\HttpKernel\Exception\HttpException $e){check('Server denies admin without module permission: '.$name,$e->getStatusCode()===403);}});}
$app['auth']->guard('admin')->setUser($admin);require __DIR__.'/../../inventory-purchasing-fixes/_checks/extend.php';file_put_contents(__DIR__.'/inventory-purchasing-regression-checks.json',json_encode($results,JSON_PRETTY_PRINT));file_put_contents(__DIR__.'/inventory-purchasing-regression-page-checks.json',json_encode($render,JSON_PRETTY_PRINT));
echo 'COMPLETED '.count($results).' checks: '.count(array_filter($results,fn($r)=>$r['result']==='PASS')).' PASS, '.count(array_filter($results,fn($r)=>$r['result']==='ISSUE')).' ISSUE, '.count(array_filter($results,fn($r)=>$r['result']==='ERROR'))." ERROR. Live DB metadata read only; fixture mutations in SQLite memory.\n";



