<?php
require __DIR__.'/bootstrap.php';
use App\Models\{Page,Post,Product,Review};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
$app['view']->getFinder()->prependLocation(__DIR__.'/../replacement-files/_staged/resources/views');
Route::get('/sitemap.xml',[App\Http\Controllers\SitemapController::class,'index'])->name('sitemap.index');Route::get('/sitemap/{type}/{page}.xml',[App\Http\Controllers\SitemapController::class,'part'])->name('sitemap.part');$app['router']->getRoutes()->refreshNameLookups();
function seoRequest($path){global $app;$r=Request::create('http://arizona.test'.$path);$r->setLaravelSession($app['session']->driver());$route=$app['router']->getRoutes()->match($r);$route->bind($r);$r->setRouteResolver(fn()=>$route);$app->instance('request',$r);return $r;}
$seo=new App\Services\PublicSeoService;
run('SEO metadata and structured data',function()use($seo){
 seoRequest('/');$values=$seo->values();check('Home receives store title',str_contains($values['title'],'Arizona')||str_contains($values['title'],config('app.name')));check('Home has a description',$values['description']!=='');check('Homepage canonical excludes tracking',!str_contains($values['canonical'],'?'));check('Organization and website schema exist',collect($values['graph'])->pluck('@type')->contains('WebSite'));
 seoRequest('/products?page=2');$values=$seo->values();check('Paginated canonical preserves page number',str_ends_with($values['canonical'],'?page=2'));check('Pagination remains indexable',str_starts_with($values['robots'],'index'));
 seoRequest('/products?q=fixture');check('Filtered shop is noindex',str_starts_with($seo->values()['robots'],'noindex'));
 seoRequest('/products?gclid=fixture');check('Ad tracking does not noindex the shop',str_starts_with($seo->values()['robots'],'index'));
 foreach(['/login','/cart','/account'] as $path){seoRequest($path);check('Private page noindex '.$path,str_starts_with($seo->values()['robots'],'noindex'));}
 $post=Post::create(['title'=>'Article SEO fixture','slug'=>'seo-article','status'=>'published','published_at'=>now()->subDay(),'meta_title'=>'Custom article title','meta_description'=>'Article description','robots_index'=>true,'robots_follow'=>true]);
 seoRequest('/seo-article');$values=$seo->values(['post'=>$post]);check('Article honors database meta title',$values['title']==='Custom article title');check('Article includes BlogPosting schema',collect($values['graph'])->pluck('@type')->contains('BlogPosting'));
 $page=Page::create(['title'=>'Policy fixture','slug'=>'policy-fixture','status'=>'published','published_at'=>now()->subDay(),'meta_title'=>'Policy database title','meta_description'=>'Policy database description']);
 seoRequest('/policy-fixture');$values=$seo->values(['page'=>$page,'post'=>$post]);check('CMS metadata wins over leaked loop post',$values['title']==='Policy database title'&&$values['type']==='website');check('CMS does not masquerade as BlogPosting',!collect($values['graph'])->pluck('@type')->contains('BlogPosting'));
 $product=Product::create(['title'=>'SEO product','slug'=>'seo-product','status'=>'active','stock'=>2,'regular_price'=>25,'sale_price'=>20,'meta_description'=>'Product description']);
 seoRequest('/product/seo-product');$values=$seo->values(['product'=>$product]);$node=collect($values['graph'])->firstWhere('@type','Product');check('Product offer uses actual sale price',$node['offers']['price']==='20.00');check('Product stock represented accurately',str_ends_with($node['offers']['availability'],'InStock'));check('No fabricated ratings',!isset($node['aggregateRating']));
 Review::create(['product_id'=>$product->id,'name'=>'Approved reviewer','email'=>'review@example.test','rating'=>4,'review'=>'Review fixture','status'=>'approved']);$node=collect($seo->values(['product'=>$product])['graph'])->firstWhere('@type','Product');check('Product rating only uses approved reviews',$node['aggregateRating']['reviewCount']===1&&$node['aggregateRating']['ratingValue']===4.0);
 $product->variants()->create(['sku'=>'SEO-VARIANT-A','stock'=>1,'regular_price'=>30,'sale_price'=>25]);$product->unsetRelation('variants');$node=collect($seo->values(['product'=>$product])['graph'])->firstWhere('@type','Product');check('Variant product reports actual offer range',$node['offers']['@type']==='AggregateOffer'&&$node['offers']['lowPrice']==='25.00');
 $sitemap=new App\Http\Controllers\SitemapController;check('Sitemap index parses',simplexml_load_string($sitemap->index()->getContent())!==false);$xml=$sitemap->part('posts',1)->getContent();check('Published article included in sitemap',str_contains($xml,'seo-article'));$post->update(['robots_index'=>false]);Post::create(['title'=>'Indexable fixture','slug'=>'seo-indexable','status'=>'published','published_at'=>now()->subDay(),'robots_index'=>true]);check('Noindex articles excluded from sitemap',!str_contains($sitemap->part('posts',1)->getContent(),'seo-article')&&str_contains($sitemap->part('posts',1)->getContent(),'seo-indexable'));
 try{$sitemap->part('products',999999);check('Out-of-range sitemap denied',false);}catch(Symfony\Component\HttpKernel\Exception\HttpException $e){check('Out-of-range sitemap denied',$e->getStatusCode()===404);}
});
run('Public HTML sanitization',function(){
 $html='<p>Allowed <strong>formatting</strong></p><img src="x" onerror="alert(1)"><script>alert(2)</script><a href="java&#x73;cript:alert(3)">Bad</a>';
 $clean=app(App\Services\HtmlContentSanitizer::class)->clean($html);check('Formatting retained',str_contains($clean,'<strong>formatting</strong>'));check('Executable HTML removed',!str_contains($clean,'onerror')&&!str_contains($clean,'<script')&&!str_contains($clean,'javascript:'));
 $product=Product::create(['title'=>'Safe rendering','slug'=>'safe-rendering','status'=>'active','stock'=>1,'regular_price'=>10,'long_description'=>$html,'additional_info'=>$html]);seoRequest('/product/safe-rendering');$render=view('products.show',['product'=>$product,'relatedProducts'=>collect()])->render();check('Existing product HTML sanitized at render',!str_contains($render,'alert(1)')&&!str_contains($render,'alert(2)'));
});
run('Blade compilation',function()use($app){$files=[];foreach([__DIR__.'/../../resources/views',__DIR__.'/../replacement-files/_staged/resources/views'] as $root)foreach(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS))as$f)if(str_ends_with($f->getFilename(),'.blade.php'))$files[]=$f->getPathname();$failed=[];foreach($files as$f){try{$app['blade.compiler']->compile($f);$output=[];$exit=0;exec(escapeshellarg(PHP_BINARY).' -l '.escapeshellarg($app['blade.compiler']->getCompiledPath($f)).' 2>&1',$output,$exit);if($exit)$failed[]=$f;}catch(Throwable){$failed[]=$f;}}check('All '.count($files).' Blade templates compile',!$failed,implode(', ',$failed));});
$failed=count(array_filter($results,fn($r)=>$r['result']!=='PASS'));file_put_contents(__DIR__.'/../seo-checks.json',json_encode($results,JSON_PRETTY_PRINT));echo count($results).' SEO/render checks; '.$failed." failures.\n";exit($failed?1:0);
