<?php
use App\Models\{InventoryHistory,PurchaseOrder,SupplierReturn};
use Illuminate\Support\Facades\{Bus};
// Included before final evidence is saved by verify.php.
run('Export consistency',function()use($reports,$variable,$v1,$valuation,$reorder,$zero){
    InventoryHistory::create(['product_id'=>$variable->id,'product_variant_id'=>$v1->id,'admin_id'=>99,'quantity_change'=>1,'stock_before'=>2,'stock_after'=>3,'movement_type'=>'restock','reason'=>'Variant export fixture']);
    ob_start();$reports->export(req())->sendContent();$csv=ob_get_clean();file_put_contents(__DIR__.'/../inventory-report-fixture.csv',$csv);
    $handle=fopen('php://temp','r+');fwrite($handle,$csv);rewind($handle);$rows=[];while(($row=fgetcsv($handle))!==false)$rows[]=$row;fclose($handle);
    check('Inventory CSV export produces header and data',count($rows)>1 && $rows[0][3]==='SKU');
    $row=collect($rows)->first(fn($r)=>($r[9]??null)==='Variant export fixture');
    check('Variant CSV uses actual variant SKU',($row[3]??null)===$v1->sku,'Expected VAR-1; actual '.($row[3]??'missing'));
    check('CSV identifies admin actor',($row[8]??null)==='Fixture admin','Actual actor '.($row[8]??'missing'));
    ob_start();$valuation->exportCsv(req(['search'=>'Zero sale']))->sendContent();$csv=ob_get_clean();check('Filtered valuation CSV executes',str_contains($csv,'Zero sale'));
    ob_start();$reorder->exportCsv(req())->sendContent();$csv=ob_get_clean();check('Reorder CSV executes',strlen($csv)>100);
    $export=new App\Exports\StockValuationExport;$row=$export->collection()->firstWhere('id',$zero->id);check('Excel valuation calculation respects zero sale',(float)$row->calculated_selling_price===0.0,'Actual '.$row->calculated_selling_price);
});
run('Report date ranges',function()use($reports){$data=$reports->index(req(['date_range'=>'custom','start_date'=>'1990-01-01','end_date'=>'1990-01-31']))->getData();check('Movement totals obey selected dates',$data['totalMovements']===0);check('Report recent movements obey selected dates',$data['recentMovements']->count()===0,'Selected 1990; recent rows='.$data['recentMovements']->count());$data=$reports->index(req(['date_range'=>'custom','start_date'=>'2026-10-02','end_date'=>'2026-10-01']))->getData();check('Inverted report dates are rejected',$data['startDate']->lte($data['endDate']),'Accepted start after end');});
run('Supplier contacts',function()use($supplier,$foreignSupplier){$controller=new App\Http\Controllers\Admin\SupplierContactController;foreach(['First','Second'] as $name){$r=req(['name'=>$name,'email'=>strtolower($name).'@example.test','is_primary'=>1]);$route=clone app('router')->getRoutes()->getByName('admin.suppliers.contacts.store');$route->bind($r);$route->setParameter('supplier',$supplier);$r->setRouteResolver(fn()=>$route);$controller->store($r,$supplier);}check('Only one primary supplier contact',$supplier->contacts()->where('is_primary',true)->count()===1);$contact=$supplier->contacts()->first();try{$controller->destroy($foreignSupplier,$contact);check('Cross-supplier contact deletion rejected',false);}catch(Symfony\Component\HttpKernel\Exception\HttpException $e){check('Cross-supplier contact deletion rejected',$e->getStatusCode()===404);}});
run('Supplier product ownership and pricing',function()use($supplier,$foreignSupplier,$simple,$v1,$purchasing){$controller=new App\Http\Controllers\Admin\SupplierProductController;$data=['product_id'=>$simple->id,'unit_cost'=>7,'minimum_order_quantity'=>5,'is_active'=>1,'is_preferred'=>1,'supplier_sku'=>'SUPPLIER-SIMPLE'];$controller->store(req($data),$supplier);$assignment=$supplier->supplierProducts()->first();check('Supplier product assignment saves price and MOQ',(float)$assignment->unit_cost===7.0 && $assignment->minimum_order_quantity===5);check('Duplicate supplier product rejected',validationBlocked(fn()=>$controller->store(req($data),$supplier)));$data['product_variant_id']=$v1->id;check('Wrong product variant assignment rejected',validationBlocked(fn()=>$controller->store(req($data),$supplier)));try{$controller->destroy($foreignSupplier,$assignment);check('Cross-supplier product deletion rejected',false);}catch(Symfony\Component\HttpKernel\Exception\HttpException $e){check('Cross-supplier product deletion rejected',$e->getStatusCode()===404);}$purchasing->store(req(['supplier_id'=>$supplier->id,'order_date'=>now()->toDateString(),'items'=>[['identifier'=>'product:'.$simple->id,'quantity'=>1,'unit_cost'=>99]]]));$po=PurchaseOrder::latest('id')->first();$item=$po->items()->first();check('Purchase item uses supplier price and minimum quantity',(float)$item->unit_cost===7.0 && $item->quantity_ordered===5 && (float)$item->line_total===35.0);});
run('Supplier ordering states',function()use($purchasing,$simple){foreach(['blocked','inactive'] as $status){$supplier=supplier(['status'=>$status]);check('Purchase creation rejects '.$status.' supplier',validationBlocked(fn()=>$purchasing->store(req(['supplier_id'=>$supplier->id,'order_date'=>now()->toDateString(),'items'=>[['identifier'=>'product:'.$simple->id,'quantity'=>1,'unit_cost'=>10]]]))));}});
run('Supplier delivery ownership',function()use($supplier,$foreignSupplier,$po2){$controller=new App\Http\Controllers\Admin\SupplierPurchaseOrderDeliveryController;try{$controller->store(req(['include_supplier_email'=>1]),$foreignSupplier,$po2);check('Purchase email cannot use another supplier',false);}catch(Symfony\Component\HttpKernel\Exception\HttpException $e){check('Purchase email cannot use another supplier',$e->getStatusCode()===404);}$controller->store(req(['include_supplier_email'=>1]),$supplier,$po2);$delivery=App\Models\SupplierPurchaseOrderDelivery::latest('id')->first();check('Supplier delivery queued without actual email',$delivery->status==='queued');check('Supplier delivery sender is actual admin model',$delivery->sentBy instanceof App\Models\Admin,'Sender relation uses '.get_debug_type($delivery->sentBy));});
run('Draft update protections',function()use($drafts,$supplier,$simple){$po=po($supplier,['status'=>'draft']);$item=line($po,$simple,2);$data=['version'=>$po->updated_at->getTimestamp()-1,'supplier_id'=>$supplier->id,'order_date'=>now()->toDateString(),'items'=>[['id'=>$item->id,'identifier'=>'product:'.$simple->id,'quantity'=>2,'unit_cost'=>12]]];check('Outdated draft version rejected',validationBlocked(fn()=>$drafts->update(req($data),$po)));$data['version']=$po->updated_at->getTimestamp();$drafts->update(req($data),$po);check('Valid draft update saves quantity and totals',$po->items()->first()->quantity_ordered===2 && (float)$po->fresh()->subtotal===24.0);});
run('Supplier returns completion',function()use($receiving,$supplier,$simple){$po=po($supplier);$item=line($po,$simple,5);$receiving->store(req(['items'=>[['purchase_order_item_id'=>$item->id,'quantity_received'=>5]]]),$po);$before=$simple->fresh()->stock;$receiving->storeReturn(req(['reason_category'=>'damaged','reason'=>'Damage audit fixture','items'=>[['purchase_order_item_id'=>$item->id,'quantity'=>1]]]),$po->fresh());$return=SupplierReturn::where('purchase_order_id',$po->id)->first();$receiving->completeReturn(req(['actual_credit'=>7]),$po,$return);check('Return completion records credit without second stock deduction',$simple->fresh()->stock===$before-1 && (float)$return->fresh()->actual_credit===7.0);check('Completed return cannot be cancelled',validationBlocked(fn()=>$receiving->cancelReturn(req(['cancellation_reason'=>'Invalid cancel']),$po,$return->fresh())));});
run('Draft version precision',function()use($drafts,$supplier,$simple){Carbon\Carbon::setTestNow('2026-10-01 12:00:00');try{$po=po($supplier,['status'=>'draft']);$item=line($po,$simple,2);$version=$po->updated_at->getTimestamp();$data=['version'=>$version,'supplier_id'=>$supplier->id,'order_date'=>now()->toDateString(),'items'=>[['id'=>$item->id,'identifier'=>'product:'.$simple->id,'quantity'=>2,'unit_cost'=>12]]];$drafts->update(req($data),$po);$data['items'][0]['quantity']=3;check('Same-second stale draft version is rejected',validationBlocked(fn()=>$drafts->update(req($data),$po)),'Version uses second-resolution updated_at');}finally{Carbon\Carbon::setTestNow();}});
run('Multi-currency purchase rows',function()use($purchasing,$simple){$usdSupplier=supplier(['currency'=>'USD']);$po=po($usdSupplier,['currency'=>'USD','total_amount'=>100]);line($po,$simple,10);$po->recalculateTotals();$html=$purchasing->index(req(['search'=>$po->reference]))->render();check('USD purchase order is displayed with its own currency',!str_contains($html,'£100.00'),'USD order 100 renders £100.00; index sums currencies without grouping');});

