@extends('admin.layouts.app')
@section('title','Menu Builder')
@section('page-heading','Menu Builder')
@section('content')
<div class="menu-page"><header class="menu-hero"><div><span>Website navigation</span><h2>Header & Footer Menu Builder</h2><p>Add CMS pages, existing website routes or custom links, then arrange their display order.</p></div></header>
@foreach($menus as $menu)
<section class="menu-panel" data-menu-panel><div class="panel-heading"><div><h3>{{ $menu->name }}</h3><p>{{ ucfirst($menu->location) }} location · {{ $menu->items->count() }} item(s)</p></div><form method="POST" action="{{ route('admin.navigation-menus.reorder',$menu) }}" data-reorder-form>@csrf @method('PUT')<div data-order-inputs></div><button><i class="fa-solid fa-arrow-down-wide-short"></i> Save order</button></form></div>
<div class="builder-grid"><div class="items-list" data-sort-list>
@forelse($menu->items as $item)<article class="menu-item-card" data-item-id="{{ $item->id }}"><div class="move-buttons"><button type="button" data-move="up" aria-label="Move up"><i class="fa-solid fa-chevron-up"></i></button><button type="button" data-move="down" aria-label="Move down"><i class="fa-solid fa-chevron-down"></i></button></div><form method="POST" action="{{ route('admin.navigation-menus.items.update',$item) }}" class="item-edit-form">@csrf @method('PUT')
<input name="label" value="{{ $item->label }}" required maxlength="100"><select name="link_type" data-link-type><option value="page" @selected($item->link_type==='page')>CMS page</option><option value="route" @selected($item->link_type==='route')>Website route</option><option value="custom" @selected($item->link_type==='custom')>Custom URL</option></select>
<select name="page_id" data-type-field="page"><option value="">Choose page</option>@foreach($pages as $page)<option value="{{ $page->id }}" @selected($item->page_id===$page->id)>{{ $page->title }}</option>@endforeach</select><select name="route_name" data-type-field="route"><option value="">Choose route</option>@foreach($routes as $name=>$label)<option value="{{ $name }}" @selected($item->route_name===$name)>{{ $label }}</option>@endforeach</select><input name="url" value="{{ $item->url }}" data-type-field="custom" placeholder="/sale or https://example.com">
<label class="check"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked($item->is_active)> Visible</label><label class="check"><input type="hidden" name="open_in_new_tab" value="0"><input type="checkbox" name="open_in_new_tab" value="1" @checked($item->open_in_new_tab)> New tab</label><button class="save-item"><i class="fa-solid fa-check"></i></button></form><form method="POST" action="{{ route('admin.navigation-menus.items.destroy',$item) }}" onsubmit="return confirm('Remove this menu item?')">@csrf @method('DELETE')<button class="delete-item"><i class="fa-regular fa-trash-can"></i></button></form></article>
@empty<div class="empty-menu"><i class="fa-solid fa-link"></i><p>No links added yet.</p></div>@endforelse
</div>
<aside class="add-item"><h3>Add menu item</h3><form method="POST" action="{{ route('admin.navigation-menus.items.store',$menu) }}" data-menu-item-form>@csrf<label>Link label<input name="label" required maxlength="100" placeholder="Shipping Policy"></label><label>Link type<select name="link_type" data-link-type><option value="page">CMS page</option><option value="route">Website route</option><option value="custom">Custom URL</option></select></label><label data-type-field="page">Published page<select name="page_id"><option value="">Choose page</option>@foreach($pages as $page)<option value="{{ $page->id }}">{{ $page->title }}</option>@endforeach</select></label><label data-type-field="route">Website route<select name="route_name"><option value="">Choose route</option>@foreach($routes as $name=>$label)<option value="{{ $name }}">{{ $label }}</option>@endforeach</select></label><label data-type-field="custom">Custom URL<input name="url" placeholder="/sale or https://example.com"></label><label class="check"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" checked> Visible</label><label class="check"><input type="hidden" name="open_in_new_tab" value="0"><input type="checkbox" name="open_in_new_tab" value="1"> Open in new tab</label><button><i class="fa-solid fa-plus"></i> Add link</button></form></aside></div></section>
@endforeach</div>
@endsection
@push('page-styles')<style>
.menu-page{display:grid;gap:18px;color:#172033}.menu-hero{padding:27px;border-radius:20px;background:linear-gradient(135deg,#172033,#7c3aed);color:#fff}.menu-hero span{color:#ddd6fe;font-size:10px;font-weight:850;letter-spacing:.14em;text-transform:uppercase}.menu-hero h2{margin:6px 0 0;font-size:30px}.menu-hero p{margin:7px 0 0;color:#ede9fe}.menu-panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:16px;background:#fff}.panel-heading{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:17px 19px;border-bottom:1px solid #e2e8f0}.panel-heading h3{margin:0}.panel-heading p{margin:4px 0 0;color:#64748b;font-size:11px}.panel-heading button,.add-item form>button{padding:9px 11px;border:0;border-radius:8px;background:#7c3aed;color:#fff;font-weight:800;cursor:pointer}.builder-grid{display:grid;grid-template-columns:minmax(0,1.7fr) minmax(280px,.7fr);align-items:start}.items-list{display:grid;gap:9px;padding:17px;border-right:1px solid #e2e8f0}.menu-item-card{display:grid;grid-template-columns:27px 1fr 32px;align-items:center;gap:8px;padding:10px;border:1px solid #e2e8f0;border-radius:11px;background:#fff}.move-buttons{display:grid;gap:3px}.move-buttons button,.save-item,.delete-item{display:grid;width:27px;height:27px;place-items:center;border:0;border-radius:6px;background:#f1f5f9;color:#64748b;cursor:pointer}.item-edit-form{display:grid;grid-template-columns:1.2fr .8fr 1.3fr auto auto 30px;align-items:center;gap:6px}.item-edit-form input,.item-edit-form select,.add-item input,.add-item select{width:100%;box-sizing:border-box;padding:8px;border:1px solid #cbd5e1;border-radius:7px;font:inherit;font-size:10px}.check{display:flex!important;align-items:center;gap:4px;white-space:nowrap;font-size:9px!important}.check input{width:auto!important}.save-item{background:#dcfce7;color:#15803d}.delete-item{background:#fff1f2;color:#be123c}.add-item{padding:18px}.add-item h3{margin:0 0 13px}.add-item form{display:grid;gap:11px}.add-item label{font-size:10px;font-weight:800}.add-item label input,.add-item label select{margin-top:5px}.empty-menu{padding:40px;text-align:center;color:#94a3b8}.empty-menu i{font-size:28px}.empty-menu p{margin:8px 0 0}@media(max-width:1100px){.builder-grid{grid-template-columns:1fr}.items-list{border-right:0;border-bottom:1px solid #e2e8f0}.item-edit-form{grid-template-columns:repeat(3,1fr)}}@media(max-width:700px){.panel-heading{align-items:stretch;flex-direction:column}.item-edit-form{grid-template-columns:1fr}.menu-item-card{align-items:start}.panel-heading button{width:100%}}
</style>@endpush
@push('page-scripts')<script>
document.querySelectorAll('[data-link-type]').forEach(function(select){function update(){const form=select.closest('form');form.querySelectorAll('[data-type-field]').forEach(function(field){const active=field.dataset.typeField===select.value;field.hidden=!active;const input=field.matches('input,select')?field:field.querySelector('input,select');if(input)input.required=active;});}select.addEventListener('change',update);update();});
document.querySelectorAll('[data-menu-panel]').forEach(function(panel){const list=panel.querySelector('[data-sort-list]');panel.querySelectorAll('[data-move]').forEach(function(button){button.addEventListener('click',function(){const item=button.closest('[data-item-id]');if(button.dataset.move==='up'&&item.previousElementSibling)item.parentNode.insertBefore(item,item.previousElementSibling);if(button.dataset.move==='down'&&item.nextElementSibling)item.parentNode.insertBefore(item.nextElementSibling,item);});});panel.querySelector('[data-reorder-form]').addEventListener('submit',function(){const holder=this.querySelector('[data-order-inputs]');holder.innerHTML='';list.querySelectorAll('[data-item-id]').forEach(function(item){const input=document.createElement('input');input.type='hidden';input.name='items[]';input.value=item.dataset.itemId;holder.appendChild(input);});});});
</script>@endpush
