
<?php $__env->startSection('title','Product Categories | Arizona Outfits'); ?>
<?php $__env->startSection('content'); ?>
<div class="page-wrapper az-category-directory"><div class="wrapper" style="padding-top:150px"><h1>Product Categories</h1><p>Explore our collections.</p></div><div class="recent-projects"><div class="wrapper"><div class="project-list az-collection-grid">
<?php $__empty_1 = true; $__currentLoopData = $categories; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $category): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
<div class="list-item"><div class="project-item"><div class="porject-image"><div class="background-image" style="background-image:url('<?php echo e(app(\App\Services\PublicMediaService::class)->url($category->featured_image)); ?>')"><div class="image-overlay"></div><div class="project-card-circle"></div></div></div><div class="project-info"><div class="project-top-info"><div class="subtitle fs-12 letter-space-4px text-uppercase text-color-white"><?php echo e($category->products_count); ?> products</div><h2 class="title fs-24 text-color-white"><?php echo e($category->title); ?></h2></div><div class="project-link"><div class="link-wrapper"><a href="<?php echo e(route('products.category',$category->slug)); ?>" class="moving-circle">View</a></div></div></div></div></div>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
<p class="az-category-empty">No product categories have been created yet.</p>
<?php endif; ?>
</div><?php echo e($categories->links()); ?></div></div></div>
<?php $__env->stopSection(); ?>
<?php $__env->startPush('page-styles'); ?><style>.az-category-directory>.wrapper{max-width:1400px;margin:0 auto;padding:150px 5vw 36px!important;box-sizing:border-box}.az-category-directory .az-collection-grid>.list-item{opacity:1!important;transform:none!important;visibility:visible!important;will-change:auto}.az-category-directory .project-info{inset:auto 24px 24px!important;padding:0!important;position:absolute!important;z-index:3;flex-direction:row!important}.az-category-empty{grid-column:1/-1;padding:32px;background:#f3f6fc;color:#64748b}.az-collection-grid{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr));gap:24px}.az-collection-grid>.list-item{margin:0!important;min-width:0}.az-collection-grid .project-item{position:relative;min-height:420px;background:#172033}.az-collection-grid .porject-image,.az-collection-grid .background-image{position:absolute;inset:0;background-size:cover;background-position:center}.az-collection-grid .image-overlay{position:absolute;inset:0;background:linear-gradient(transparent,#090b19cc)}.az-collection-grid .project-info{position:absolute;bottom:24px;left:24px;right:24px;display:flex;align-items:end;justify-content:space-between;gap:12px}.az-collection-grid .title{overflow-wrap:anywhere}.az-collection-grid .moving-circle{width:70px;height:70px;border:1px solid white;color:white;border-radius:50%;display:grid;place-items:center;text-decoration:none;transition:background .25s}.az-collection-grid .moving-circle:hover{background:#ffffff30}@media(max-width:900px){.az-collection-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.az-collection-grid{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){.az-collection-grid *{transition:none!important}}</style><?php $__env->stopPush(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>