<?php
require __DIR__.'/bootstrap.php';
use App\Models\{User,Order,OrderNote,OrderActivity,Product,Review,CustomerEmailIdentity};
use Illuminate\Support\Facades\{Auth,Schema,Hash,URL,DB};
$customer=customerFixture();$otherCustomer=customerFixture();$product=Product::create(['title'=>'Customer sync product','slug'=>'customer-sync-product','sku'=>'CUS-1','status'=>'active','regular_price'=>100,'stock'=>20]);
$dashboard=new App\Http\Controllers\CustomerDashboardController;
$paid=Order::create(['user_id'=>$customer->id,'order_number'=>'SYNC-PAID','tracking_number'=>'TRK-SYNC','payment_status'=>'paid','order_status'=>'completed','currency'=>'GBP','subtotal'=>100,'total'=>100,'billing_name'=>$customer->name,'billing_email'=>$customer->email,'shipping_email'=>$customer->email,'payment_method'=>'cash_on_delivery']);
$paid->items()->create(['product_id'=>$product->id,'product_title'=>$product->title,'sku'=>'CUS-1','price'=>100,'quantity'=>1,'total'=>100]);
$archived=Order::create(['user_id'=>$customer->id,'order_number'=>'SYNC-ARCHIVED','payment_status'=>'paid','order_status'=>'delivered','currency'=>'GBP','total'=>20]);$archived->delete();
$foreign=Order::create(['user_id'=>$otherCustomer->id,'order_number'=>'SYNC-FOREIGN','payment_status'=>'pending','order_status'=>'pending','currency'=>'USD','total'=>500]);
run('Order ownership and archive synchronization',function()use($customer,$otherCustomer,$paid,$archived,$foreign,$dashboard){
 $r=customerRequest($customer);$data=$dashboard->index($r)->getData();check('Customer overview counts own active and archived orders',$data['stats']['orders']===2);check('Overview does not count another customer order',$data['recentOrders']->every(fn($order)=>$order->user_id===$customer->id));
 $list=$dashboard->orders(customerRequest($customer,[],'customer.orders.index'))->getData()['orders'];check('Customer order list includes archived purchase',$list->contains('id',$archived->id));
 $list=$dashboard->orders(customerRequest($customer,['search'=>'TRK-SYNC'],'customer.orders.index'))->getData()['orders'];check('Order search matches tracking number',$list->count()===1 && $list->first()->id===$paid->id);
 check('Invalid order filter rejected',validationBlocked(fn()=>$dashboard->orders(customerRequest($customer,['status'=>'bad'],'customer.orders.index'))));
 foreach(['show','invoice','downloadInvoice']as $method)check('Cross-customer access denied: '.$method,mustDeny(fn()=>$dashboard->$method(customerRequest($customer),$foreign->id)));
 check('Archived customer order detail remains accessible',$dashboard->show(customerRequest($customer),$archived->id)->getData()['order']->id===$archived->id);
 $adminData=(new App\Http\Controllers\Admin\CustomerController)->show($customer)->getData();check('Admin and customer order counts agree',$adminData['customer']->orders->count()===$data['stats']['orders']);check('Admin spending includes archived paid total',$adminData['totalSpent']===['GBP'=>120.0]);
});
run('Admin order updates and customer privacy',function()use($customer,$paid,$dashboard){
 $activity=new App\Services\OrderActivityService;$activity->orderStatusChanged($paid,'processing','completed');$activity->paymentStatusChanged($paid,'pending','paid');
 OrderActivity::create(['order_id'=>$paid->id,'type'=>'order_updated','title'=>'Internal fixture activity','description'=>'PRIVATE-ACTIVITY-SENTINEL']);
 OrderNote::create(['order_id'=>$paid->id,'note'=>'PUBLIC-NOTE-SENTINEL','is_customer_visible'=>true]);OrderNote::create(['order_id'=>$paid->id,'note'=>'PRIVATE-NOTE-SENTINEL','is_customer_visible'=>false]);$paid->update(['admin_notes'=>'PRIVATE-ADMIN-SENTINEL','order_notes'=>'Customer checkout note']);
 $view=$dashboard->show(customerRequest($customer,[],'customer.orders.show'),$paid->id);$data=$view->getData()['order'];
 check('Customer reads current admin payment/order states',$data->payment_status==='paid' && $data->order_status==='completed');check('Customer sees allowed status/payment history',$data->activities->contains('type','payment_status_changed') && $data->activities->contains('type','order_status_changed'));check('Internal activity excluded',$data->activities->every(fn($a)=>$a->type!=='order_updated'));check('Only customer-visible admin notes returned',$data->notes->count()===1 && $data->notes->first()->note==='PUBLIC-NOTE-SENTINEL');
 $html=$view->render();check('Customer order HTML hides admin/private notes',!str_contains($html,'PRIVATE-NOTE-SENTINEL')&&!str_contains($html,'PRIVATE-ADMIN-SENTINEL')&&!str_contains($html,'PRIVATE-ACTIVITY-SENTINEL'));check('Visible admin note appears in customer HTML',str_contains($html,'PUBLIC-NOTE-SENTINEL'));
});
run('Public tracking and thank-you privacy',function()use($customer,$otherCustomer,$paid,$archived){
 $tracking=new App\Http\Controllers\OrderTrackingController;$r=customerRequest($customer,['order_number'=>$paid->order_number,'email'=>'wrong@example.test'],'orders.track.lookup','POST');check('Tracking refuses wrong customer email',$tracking->lookup($r) instanceof Illuminate\Http\RedirectResponse);
 $r=customerRequest($customer,['order_number'=>strtolower($paid->order_number),'email'=>$customer->email],'orders.track.lookup','POST');$view=$tracking->lookup($r);check('Public tracking accepts matching order plus email',$view instanceof Illuminate\View\View && $view->getData()['order']->id===$paid->id);check('Tracking hides internal activity and notes',!str_contains($view->render(),'PRIVATE-NOTE-SENTINEL'));
 $checkout=app(App\Http\Controllers\CheckoutController::class);customerRequest($otherCustomer);app('session')->forget('recent_order_number');check('Other customer cannot open thank-you page',mustDeny(fn()=>$checkout->thankYou($paid->order_number),403));customerRequest($customer);check('Owner can open current order thank-you page',$checkout->thankYou($paid->order_number)->getData()['order']->id===$paid->id);check('Archived order thank-you remains consistent with My Orders',!mustDeny(fn()=>$checkout->thankYou($archived->order_number)));
});
run('Admin customer status and dual sessions',function()use($customer){
 $controller=new App\Http\Controllers\Admin\CustomerController;$controller->update(customerRequest($customer,['name'=>'Admin updated customer','status'=>'blocked'],'customer.dashboard','POST'),$customer);$customer->refresh();check('Admin name update reaches customer profile',$customer->name==='Admin updated customer');
 $r=customerRequest($customer);$r->headers->set('Accept','application/json');$webKey=Auth::guard('web')->getName();$adminKey=Auth::guard('admin')->getName();$r->session()->put($webKey,$customer->id);$r->session()->put($adminKey,99);
 $response=(new App\Http\Middleware\CustomerAccountStatus)->handle($r,fn()=>response('allowed'));check('Admin-blocked customer is denied next request',$response->getStatusCode()===403);check('Blocked customer loses only customer login',!$r->session()->has($webKey) && $r->session()->get($adminKey)===99);
 $customer->update(['status'=>'active']);$r=customerRequest($customer);$r->session()->put($webKey,$customer->id);$r->session()->put($adminKey,99);(new App\Http\Controllers\Auth\AuthenticatedSessionController)->destroy($r);check('Normal customer logout preserves admin session',$r->session()->get($adminKey)===99 && !$r->session()->has($webKey));
});
run('Favorites and review moderation synchronization',function()use($customer,$otherCustomer,$product){
 $favorites=new App\Http\Controllers\FavoriteController;$favorites->toggle(customerRequest($customer,['product_id'=>$product->id],'favorite.toggle','POST'));check('Favorite added for current customer',App\Models\Favorite::where('user_id',$customer->id)->where('product_id',$product->id)->exists());customerRequest($otherCustomer);check('Another customer cannot see favorites',$favorites->index()->getData()['favorites']->isEmpty());$favorites->toggle(customerRequest($customer,['product_id'=>$product->id],'favorite.toggle','POST'));check('Favorite toggle removes only own item',!App\Models\Favorite::where('user_id',$customer->id)->exists());
 $review=Review::create(['user_id'=>$customer->id,'product_id'=>$product->id,'rating'=>4,'review'=>'Fixture review','status'=>'pending']);check('Pending customer review hidden publicly',!Review::approved()->whereKey($review->id)->exists());$review->update(['status'=>'approved']);check('Admin approval publishes same customer review',Review::approved()->whereKey($review->id)->exists());$review->update(['status'=>'rejected']);check('Admin rejection hides review again',!Review::approved()->whereKey($review->id)->exists());
});
run('Verified email change and actual login identity',function(){
 $u=customerFixture();$oldEmail=$u->email;$newEmail='changed-sync@example.test';$u->forceFill(['pending_email'=>$newEmail,'pending_email_requested_at'=>now()])->save();
 $url=URL::temporarySignedRoute('customer.security.email.change.verify',now()->addMinutes(20),['user'=>$u->id,'email'=>$newEmail]);$r=Illuminate\Http\Request::create($url,'GET');$r->setLaravelSession(app('session')->driver());$r->setUserResolver(fn()=>$u);app()->instance('request',$r);Auth::shouldUse('web');Auth::guard('web')->setUser($u);
 (new App\Http\Controllers\Customer\AccountSecurityController)->verifyEmailChange($r,$u);$u->refresh();check('Verified email updates admin customer contact',$u->email===$newEmail);
 $identity=$u->customEmailIdentity();check('Verified email updates custom login identity',$identity->normalized_email===$newEmail && $identity->email===$newEmail);
 foreach([$newEmail=>true,$oldEmail=>false]as $email=>$shouldWork){$login=App\Http\Requests\Auth\LoginRequest::create('/login','POST',['email'=>$email,'password'=>'FixturePassword123!']);$login->setContainer(app());$login->setRedirector(app('redirect'));$login->setLaravelSession(app('session')->driver());app()->instance('request',$login);$allowed=!validationBlocked(fn()=>$login->authenticate());check($shouldWork?'New verified email can sign in':'Previous email can no longer sign in',$allowed===$shouldWork);}
});
run('Password routes share security history',function(){
 $u=customerFixture();$original=$u->password;$r=customerRequest($u,['current_password'=>'FixturePassword123!','password'=>'AnotherPassword456!','password_confirmation'=>'AnotherPassword456!'],'password.update','PUT');
 (new App\Http\Controllers\Auth\PasswordController)->update($r);$u->refresh();check('Standard password route records password history',$u->passwordHistories()->count()===1 && Hash::check('FixturePassword123!',$u->passwordHistories()->latest('id')->value('password')??''));
 $security=new App\Http\Controllers\Customer\AccountSecurityController;$r=customerRequest($u,['current_password'=>'AnotherPassword456!','password'=>'FixturePassword123!','password_confirmation'=>'FixturePassword123!'],'customer.security.password.update','POST');check('Security route blocks previous password after standard password update',validationBlocked(fn()=>$security->updatePassword($r,new App\Services\PasswordSecurityService)));
});
run('Account deletion agrees with admin retention/session rules',function(){
 $u=customerFixture();$order=Order::create(['user_id'=>$u->id,'order_number'=>'DELETION-HISTORY','payment_status'=>'paid','order_status'=>'completed','currency'=>'USD','total'=>40]);$order->delete();$r=customerRequest($u,['password'=>'FixturePassword123!'],'profile.destroy','DELETE');$adminKey=Auth::guard('admin')->getName();$r->session()->put($adminKey,99);$controller=new App\Http\Controllers\ProfileController;
 $blocked=validationBlocked(fn()=>$controller->destroy($r));check('Customer deletion respects archived order history like admin deletion',$blocked && User::find($u->id)!==null);check('Customer deletion preserves independent admin session',$r->session()->get($adminKey)===99);
});
run('Installed shared dependencies',function(){
 check('Admin/customer synchronization dependency AdminAccessPolicy exists',class_exists(App\Services\AdminAccessPolicy::class));check('Receipt administrator relation is installed',method_exists(App\Models\PurchaseOrderReceipt::class,'receiverAdmin'));
});
$pages=['Overview'=>fn()=>$dashboard->index(customerRequest($customer)),'My Orders'=>fn()=>$dashboard->orders(customerRequest($customer,[],'customer.orders.index')),'Order Detail'=>fn()=>$dashboard->show(customerRequest($customer,[],'customer.orders.show'),$paid->id),'Invoice'=>fn()=>$dashboard->invoice(customerRequest($customer,[],'customer.orders.invoice'),$paid->id),'Profile'=>fn()=>(new App\Http\Controllers\ProfileController)->edit(customerRequest($customer,[],'profile.edit')),'Login and Security'=>fn()=>(new App\Http\Controllers\Customer\AccountSecurityController)->index(customerRequest($customer,[],'customer.security'),new App\Services\CustomerLoginSecurity),'Favorites'=>function()use($customer){customerRequest($customer,[],'favorites.index');return (new App\Http\Controllers\FavoriteController)->index();},'Public Tracking'=>fn()=>(new App\Http\Controllers\OrderTrackingController)->index()];
$renders=[];foreach($pages as $label=>$action)run('Render '.$label,function()use($label,$action,&$renders){$html=$action()->render();$renders[$label]=['pass'=>strlen($html)>500,'bytes'=>strlen($html)];check('Installed customer page renders: '.$label,strlen($html)>500);});
file_put_contents(__DIR__.'/../checks.json',json_encode($results,JSON_PRETTY_PRINT));file_put_contents(__DIR__.'/../page-checks.json',json_encode($renders,JSON_PRETTY_PRINT));echo 'CUSTOMER AUDIT '.count($results).' checks: '.count(array_filter($results,fn($r)=>$r['result']==='PASS')).' PASS; '.count(array_filter($results,fn($r)=>$r['result']==='ISSUE')).' ISSUE; '.count(array_filter($results,fn($r)=>$r['result']==='ERROR'))." test errors. Current installed source; SQLite fixtures only.\n";
