<?php
require __DIR__.'/bootstrap.php';
use App\Models\{Admin,AdminRole,AdminPermission,EcommerceSetting,Page,NavigationMenu,NavigationMenuItem,Order,OrderItem,AdminAuditLog,AdminBackup,EmailTemplate};
use App\Services\{CmsContentSanitizer,NavigationMenuService,EmailTemplateService};
use Illuminate\Support\Facades\{Auth,DB,Storage,Notification};

run('Store Settings',function(){
 $controller=new App\Http\Controllers\Admin\EcommerceSettingController;$settings=EcommerceSetting::current();
 $data=['store_name'=>'Fixture Store','currency'=>'USD','currency_symbol'=>'$','tax_percentage'=>12,'shipping_fee'=>17,'order_prefix'=>'TEST','low_stock_threshold'=>22,'bank_transfer_enabled'=>1];$controller->update(req($data));check('Store settings update saves numeric and checkbox values',(float)$settings->fresh()->tax_percentage===12.0 && !$settings->fresh()->guest_checkout_enabled && $settings->fresh()->bank_transfer_enabled);
 check('Settings reject tax above 100',validationBlocked(fn()=>$controller->update(req(array_replace($data,['tax_percentage'=>101])))));
 check('Saved default inventory threshold reaches inventory service',App\Services\InventoryCatalogService::threshold(new App\Models\Product)===22,'Saved threshold 22; service threshold '.App\Services\InventoryCatalogService::threshold(new App\Models\Product));
});
run('CMS pages and Menu Builder',function()use($app){
 $controller=new App\Http\Controllers\Admin\AdminPageController;$sanitizer=new CmsContentSanitizer;
 $data=['title'=>'Fixture Page','render_mode'=>'editor','content'=>'<h1>Safe content</h1><script>alert(1)</script><p onclick="bad()">Paragraph</p>','status'=>'draft','template'=>'default'];$controller->store(req($data),$sanitizer);$page=Page::latest('id')->first();
 check('CMS page stores separate admin ownership',$page->creator_admin_id===99 && $page->created_by===null);check('CMS removes script tags and event attributes',!str_contains($page->content,'<script') && !str_contains($page->content,'onclick'));check('Draft CMS page stays private',!Page::published()->whereKey($page->id)->exists());
 $data['status']='published';$controller->update(req($data),$page,$sanitizer);$page->refresh();check('CMS publication sets public date',Page::published()->whereKey($page->id)->exists());check('Public CMS controller renders published content',str_contains((new App\Http\Controllers\CmsPageController)->show($page->slug)->render(),'Safe content'));
 try{$route=$app['router']->getRoutes()->match(Illuminate\Http\Request::create('/page/'.$page->slug));check('Public CMS URL accepts normal slug',$route->getName()==='pages.show');}catch(Symfony\Component\HttpKernel\Exception\HttpException){check('Public CMS URL accepts normal slug',false,'Normal slug fails route regex');}
 check('Custom page requires an existing Blade template',validationBlocked(fn()=>$controller->store(req(array_replace($data,['render_mode'=>'custom','blade_template'=>'not-present'])),$sanitizer)));
 $menu=NavigationMenu::where('location','header')->first();$menus=new App\Http\Controllers\Admin\AdminNavigationMenuController;$service=new NavigationMenuService;
 $menus->storeItem(req(['label'=>'Fixture page','link_type'=>'page','page_id'=>$page->id,'is_active'=>1]),$menu,$service);$item=$menu->items()->first();check('Menu page link resolves to CMS URL',$item->resolved_url===$page->public_url);
 check('Menu refuses javascript custom URL',validationBlocked(fn()=>$menus->storeItem(req(['label'=>'Bad link','link_type'=>'custom','url'=>'javascript:alert(1)']),$menu,$service)));
 $bad='/\\evil.example/path';check('Menu rejects backslash authority bypass',validationBlocked(fn()=>$menus->storeItem(req(['label'=>'Bad slash link','link_type'=>'custom','url'=>$bad]),$menu,$service)));
 check('Menu reorder rejects duplicate IDs',validationBlocked(fn()=>$menus->reorder(req(['items'=>[$item->id,$item->id]]),$menu,$service)),'Duplicate item IDs accepted');
 $service->items('header');$controller->update(req(array_replace($data,['slug'=>'changed-fixture-page'])),$page,$sanitizer);$page->refresh();check('CMS edits invalidate cached menu URLs',$service->items('header')->first()->resolved_url===$page->public_url,'Cached menu retains former page slug');
 $controller->update(req(array_replace($data,['status'=>'draft'])),$page,$sanitizer);$cache=$service->items('header');$menus->updateItem(req(['label'=>'Updated label','link_type'=>'page','page_id'=>$page->id,'is_active'=>1]),$item,$service);check('Menu update clears location cache',$service->items('header')->first()->label==='Updated label');
 $draftItem=$service->items('header')->first();check('Menu hides unpublished page target',$draftItem->resolved_url==='#');$menus->destroyItem($item,$service);check('Menu deletion removes item',NavigationMenuItem::find($item->id)===null);
});
run('Analytics archived and mixed-currency consistency',function(){
 $a=Order::create(['user_id'=>1,'order_number'=>'ANALYTICS-ARCHIVE','total'=>40,'discount'=>0,'currency'=>'USD','payment_status'=>'paid','order_status'=>'completed']);$a->delete();$b=Order::create(['user_id'=>1,'order_number'=>'ANALYTICS-LIVE','total'=>20,'discount'=>0,'currency'=>'USD','payment_status'=>'paid','order_status'=>'completed']);
 foreach([$a,$b] as $order)$order->items()->create(['product_title'=>'Fixture sold item','sku'=>'AUDIT','price'=>10,'quantity'=>1,'total'=>10]);
 $controller=new App\Http\Controllers\Admin\AdminAnalyticsController;$data=$controller->index(req())->getData();check('Analytics keeps archived paid revenue',(float)$data['metrics']['revenue']['value']===60.0,'Actual '.$data['metrics']['revenue']['value']);check('Analytics top products agrees with total sold units',(int)$data['metrics']['items']['value']===(int)$data['topProducts']->sum('units'),'Summary='.$data['metrics']['items']['value'].'; product rows='.$data['topProducts']->sum('units'));
 Order::create(['user_id'=>1,'total'=>25,'currency'=>'GBP','payment_status'=>'paid','order_status'=>'completed']);$data=$controller->index(req())->getData();check('Analytics separates revenue by currency',isset($data['currencyTotals']) || isset($data['metrics']['revenue']['currencies']),'Current scalar revenue combines currencies');
 check('Analytics rejects malformed dates',validationBlocked(fn()=>$controller->index(req(['start_date'=>'bad-date']))));
 ob_start();$controller->export(req())->sendContent();$csv=ob_get_clean();check('Analytics CSV export runs',str_contains($csv,'Daily performance'));
});
run('Admin Team and Roles',function()use($admin){
 $roles=new App\Http\Controllers\Admin\AdminRoleController;$permission=AdminPermission::where('slug','dashboard.view')->first();$roles->store(req(['name'=>'Fixture role','permission_ids'=>[$permission->id]]));$role=AdminRole::where('name','Fixture role')->first();check('Role creation saves selected permissions',$role->permissions()->count()===1);
 check('Duplicate role permission IDs rejected',validationBlocked(fn()=>$roles->store(req(['name'=>'Duplicate role','permission_ids'=>[$permission->id,$permission->id]]))));
 $team=new App\Http\Controllers\Admin\AdminUserController;$team->store(req(['mode'=>'create','name'=>'Fixture staff','email'=>'staff@example.test','password'=>'FixturePassword123!','password_confirmation'=>'FixturePassword123!','status'=>'active','role_ids'=>[$role->id]]));$staff=Admin::where('email','staff@example.test')->first();check('New administrator assigned independent admin role',$staff->adminRoles()->whereKey($role->id)->exists() && $staff->hasAdminPermission('dashboard.view'));
 $roles->destroy($role);check('Assigned role cannot be deleted',AdminRole::find($role->id)!==null);$system=AdminRole::where('is_system',true)->first();$roles->destroy($system);check('System role cannot be deleted',AdminRole::find($system->id)!==null);
 $team->destroy($admin);check('Cannot revoke own administrator account',Admin::find($admin->id)!==null);
 check('Last super administrator cannot be demoted',validationBlocked(fn()=>$team->update(req(['name'=>'Fixture admin','email'=>'admin@example.test','status'=>'active','is_super_admin'=>0,'role_ids'=>[$role->id]]),$admin)));
 $customer=App\Models\User::create(['name'=>'Promotion customer','email'=>'promote@example.test','password'=>'FixturePassword123!','status'=>'active']);$old=$customer->fresh()->getRawOriginal();$team->store(req(['mode'=>'promote','existing_user_id'=>$customer->id,'status'=>'active','role_ids'=>[$role->id]]));check('Promotion preserves original customer',$customer->fresh()->getRawOriginal()===$old);check('Promotion preserves password hash',Admin::where('email','promote@example.test')->first()->getRawOriginal('password')===$customer->getRawOriginal('password'));
 $roles->update(req(['name'=>'Renamed role','permission_ids'=>[AdminPermission::where('slug','reviews.manage')->value('id')]]),$role);$staff->flushAdminPermissionCache();check('Role updates change permissions after cache refresh',$staff->hasAdminPermission('reviews.manage') && !$staff->hasAdminPermission('dashboard.view'));
});
run('Notification ownership and action URLs',function()use($admin){
 $other=Admin::where('email','staff@example.test')->first();$admin->notify(new App\Notifications\AdminSystemNotification('Own notification','Own message'));$other->notify(new App\Notifications\AdminSystemNotification('Foreign notification','Foreign message'));$controller=new App\Http\Controllers\Admin\AdminNotificationController;$own=$admin->notifications()->first();$foreign=$other->notifications()->first();
 check('Notification list belongs to current admin',$controller->index(req())->getData()['notifications']->count()===1);try{$controller->destroy(req(),$foreign->id);check('Cannot delete another admin notification',false);}catch(Illuminate\Database\Eloquent\ModelNotFoundException){check('Cannot delete another admin notification',true);}
 $controller->markAsRead(req(),$own->id);check('Notification read changes unread count',$admin->unreadNotifications()->count()===0);
 $data=['recipient'=>'all','title'=>'Fixture broadcast','message'=>'Fixture audit notification','level'=>'info','action_url'=>'/\\evil.example'];Notification::fake();$appSession=app('session')->driver();$appSession->forget(['success','error','errors']);$response=$controller->send(req($data));check('Notification rejects backslash redirect URL',!$response->getSession()->has('success') && $response->getSession()->has('errors'),'Unsafe slash URL accepted');
 $data['action_url']='ftp://arizona.test/unsafe';$response=$controller->send(req($data));check('Notification rejects non-HTTP same-host URL',$response->getSession()->has('errors'),'Same host accepted without scheme restriction');
 $controller->clearRead(req());check('Clear-read leaves other admin notifications',$other->notifications()->count()===1);
});
run('Audit trail ownership and redaction',function()use($app){
 $r=req(['password'=>'secret-fixture','nested'=>['account_number'=>'123456','safe'=>'visible']]);$route=clone $app['router']->getRoutes()->getByName('admin.settings.update');$route->bind($r);$r->setRouteResolver(fn()=>$route);$middleware=new App\Http\Middleware\AdminAuditMiddleware;$middleware->handle($r,fn()=>response('okay'));$log=AdminAuditLog::latest('id')->first();check('Audit trail records true administrator',$log && $log->admin_id===99 && $log->user_id===null);check('Audit redacts nested secrets',$log->request_data['input']['password']==='[REDACTED]' && $log->request_data['input']['nested']['account_number']==='[REDACTED]');
 try{$middleware->handle($r,fn()=>throw Illuminate\Validation\ValidationException::withMessages(['name'=>'Invalid input']));}catch(Illuminate\Validation\ValidationException){}$log=AdminAuditLog::latest('id')->first();check('Audit records validation as 422 rather than 500',$log->status_code===422,'Actual '.$log->status_code);
 $controller=new App\Http\Controllers\Admin\AdminAuditLogController;check('Audit administrator search works',$controller->index(req(['search'=>'Fixture admin']))->getData()['logs']->count()>=1);ob_start();$controller->export(req())->sendContent();$csv=ob_get_clean();check('Audit CSV identifies admin',str_contains($csv,'Fixture admin'));
});
run('Backups preserve earlier snapshots on same-second failure',function()use($app){
 $previous=$app->storagePath();$app->useStoragePath(__DIR__.'/files/test-storage');Carbon\Carbon::setTestNow('2026-10-02 12:00:00');try{
 $path='admin-backups/arizona-outfits_database_'.now()->format('Y-m-d_H-i-s').'.sql.gz';Storage::disk('local')->put($path,'existing fixture backup');$backup=AdminBackup::create(['name'=>basename($path),'type'=>'database','disk'=>'local','file_path'=>$path,'status'=>'completed','admin_id'=>99]);
 try{app(App\Services\AdminBackupService::class)->create('database',99);}catch(RuntimeException){}
 check('Failed repeated backup cannot delete earlier completed archive',Storage::disk('local')->exists($path),'Same-second failure removes shared path');check('Backup filenames unique between same-second attempts',AdminBackup::where('file_path',$path)->count()===1,'Multiple records share file path');
 check('Backup failure retained as failed record',AdminBackup::where('status','failed')->exists());
 }finally{Carbon\Carbon::setTestNow();$app->useStoragePath($previous);}
});
run('Email templates',function(){
 $controller=new App\Http\Controllers\Admin\AdminEmailTemplateController;$service=new EmailTemplateService;$template=EmailTemplate::first();$controller->update(req(['subject'=>'Order {{order_number}}','body'=>'<p>Hello {{customer_name}}</p>','is_enabled'=>1]),$template);check('Email update records administrator',$template->fresh()->admin_id===99 && $template->fresh()->updated_by===null);
 check('Unknown compact template variables rejected',validationBlocked(fn()=>$controller->update(req(['subject'=>'Test','body'=>'{{unknown}}']),$template)));
 check('Unknown spaced template variables rejected',validationBlocked(fn()=>$controller->update(req(['subject'=>'Test','body'=>'{{ unknown }}']),$template)));
 check('HTML template variables escaped',str_contains($service->replace('<p>{{customer_name}}</p>',['customer_name'=>'<script>bad</script>']), '&lt;script&gt;'));
 $template->update(['is_enabled'=>false]);check('Disabled template uses built-in fallback',$service->render($template->slug,[],'Fallback','emails.orders.customer-confirmation')['html']===null);
 check('Email preview renders sample content',strlen($controller->preview($template,$service)->render())>100);
});
run('CMS sanitizer URL bypasses',function(){
 $html=(new CmsContentSanitizer)->clean('<a href=javascript:alert(1)>Unquoted</a><a href="java&#x73;cript:alert(1)">Encoded</a>');$doc=new DOMDocument;@$doc->loadHTML($html);$unsafe=false;foreach($doc->getElementsByTagName('a') as $anchor)if(str_starts_with(strtolower($anchor->getAttribute('href')),'javascript:'))$unsafe=true;check('CMS sanitizer rejects executable encoded/unquoted links',!$unsafe);
});
$pages=['Store Settings'=>fn()=>(new App\Http\Controllers\Admin\EcommerceSettingController)->edit(),'CMS Pages'=>fn()=>(new App\Http\Controllers\Admin\AdminPageController)->index(req()),'CMS create'=>fn()=>(new App\Http\Controllers\Admin\AdminPageController)->create(),'CMS edit'=>fn()=>(new App\Http\Controllers\Admin\AdminPageController)->edit(Page::first()),'Menu Builder'=>fn()=>(new App\Http\Controllers\Admin\AdminNavigationMenuController)->index(),'Global Analytics'=>fn()=>(new App\Http\Controllers\Admin\AdminAnalyticsController)->index(req()),'Admin Team'=>fn()=>(new App\Http\Controllers\Admin\AdminUserController)->index(req()),'Admin edit'=>fn()=>(new App\Http\Controllers\Admin\AdminUserController)->edit(Admin::find(99)),'Roles'=>fn()=>(new App\Http\Controllers\Admin\AdminRoleController)->index(),'Notifications'=>fn()=>(new App\Http\Controllers\Admin\AdminNotificationController)->index(req()),'Audit logs'=>fn()=>(new App\Http\Controllers\Admin\AdminAuditLogController)->index(req()),'Backups'=>fn()=>(new App\Http\Controllers\Admin\AdminBackupController)->index(),'Email Templates'=>fn()=>(new App\Http\Controllers\Admin\AdminEmailTemplateController)->index(),'Email edit'=>fn()=>(new App\Http\Controllers\Admin\AdminEmailTemplateController)->edit(EmailTemplate::first())];$render=[];
foreach($pages as $label=>$factory){try{$html=$factory()->render();$render[$label]=['result'=>'PASS','bytes'=>strlen($html)];check('Page render: '.$label,strlen($html)>500);}catch(Throwable $e){$render[$label]=['result'=>'ERROR','detail'=>$e->getMessage()];check('Page render: '.$label,false,get_class($e).' '.$e->getMessage());}}
foreach(['admin.settings.update','admin.pages.store','admin.navigation-menus.items.store','admin.analytics.index','admin.admin-users.store','admin.admin-roles.store','admin.notifications.send','admin.audit-logs.export','admin.backups.download','admin.email-templates.update'] as $name)run('Permission '.$name,function()use($app,$name){$mock=Mockery::mock(Admin::class)->makePartial();$mock->shouldReceive('isActive')->andReturn(true);$mock->shouldReceive('hasAdminPermission')->andReturn(false);Auth::guard('admin')->setUser($mock);$r=req();$r->setRouteResolver(fn()=>$app['router']->getRoutes()->getByName($name));try{(new App\Http\Middleware\AdminMiddleware)->handle($r,fn()=>response('allowed'));check('Unauthorized admin denied: '.$name,false);}catch(Symfony\Component\HttpKernel\Exception\HttpException $e){check('Unauthorized admin denied: '.$name,$e->getStatusCode()===403);}});AuthFix();
file_put_contents(__DIR__.'/../checks.json',json_encode($results,JSON_PRETTY_PRINT));file_put_contents(__DIR__.'/../page-render-checks.json',json_encode($render,JSON_PRETTY_PRINT));echo 'COMPLETED '.count($results).' checks: '.count(array_filter($results,fn($r)=>$r['result']==='PASS')).' PASS, '.count(array_filter($results,fn($r)=>$r['result']==='ISSUE')).' ISSUE, '.count(array_filter($results,fn($r)=>$r['result']==='ERROR'))." ERROR. SQLite memory and fixture files only.\n";
