<?php
require __DIR__.'/bootstrap.php';
use Illuminate\Support\Facades\{Auth,Storage};
use App\Models\{User,Product,Review,Post,Category,Order};
run('Existing disabled customer sessions',function()use($app,$admin){
 $middleware=new App\Http\Middleware\CustomerAccountStatus;$user=User::create(['name'=>'Disabled session','email'=>'disabled@example.test','status'=>'blocked']);Auth::guard('web')->setUser($user);Auth::guard('admin')->setUser($admin);
 $r=Illuminate\Http\Request::create('http://arizona.test/account');$r->setLaravelSession($app['session']->driver());$called=false;$response=$middleware->handle($r,function()use(&$called){$called=true;return response('allowed');});
 check('Blocked existing session loses account access',!$called && $response->getStatusCode()===302 && Auth::guard('web')->guest());check('Administrator session preserved',Auth::guard('admin')->id()===99);
 Auth::guard('web')->setUser($user);$r=Illuminate\Http\Request::create('http://arizona.test/admin/customers');$r->setLaravelSession($app['session']->driver());$response=$middleware->handle($r,fn()=>response('admin allowed'));check('Coexisting disabled customer cannot interrupt admin dashboard',$response->getContent()==='admin allowed' && Auth::guard('admin')->id()===99);
 Auth::guard('web')->setUser($user);$r=Illuminate\Http\Request::create('http://arizona.test/account','GET',[],[],[],['HTTP_ACCEPT'=>'application/json']);$r->setLaravelSession($app['session']->driver());check('Disabled JSON request returns 403',$middleware->handle($r,fn()=>response('allowed'))->getStatusCode()===403);
 Auth::guard('web')->setUser(User::find(1));check('Active customer still allowed',$middleware->handle($r,fn()=>response('active'))->getContent()==='active');Auth::shouldUse('admin');
});
run('Phone account and guest reviews',function(){
 $product=Product::create(['title'=>'Phone review item','slug'=>'phone-review-item','status'=>'active']);$user=User::create(['name'=>'Phone customer','email'=>'','phone'=>'+923001112222','status'=>'active']);Auth::guard('web')->setUser($user);Auth::shouldUse('web');$controller=new App\Http\Controllers\ReviewController;
 check('Phone customer required email validated',validationBlocked(fn()=>$controller->store(req(['rating'=>4,'review'=>'A sufficiently long review from phone user']),$product)));
 $controller->store(req(['email'=>'phone-review@example.test','rating'=>4,'review'=>'A sufficiently long review from phone user']),$product);$review=Review::latest('id')->first();check('Phone review retains customer ID and contact email',$review->user_id===$user->id && $review->email==='phone-review@example.test' && $review->status==='pending');
 $html=(new App\Http\Controllers\ShopController)->show($product->slug)->render();check('Phone customer sees email input',str_contains($html,'id="review-email"'));
 Auth::guard('web')->forgetUser();$data=['name'=>'Guest','email'=>'Guest@Example.test','rating'=>5,'review'=>'A sufficiently long guest product review'];$controller->store(req($data),$product);$before=Review::count();$data['email']='guest@example.test';$controller->store(req($data),$product);check('Guest duplicates use case insensitive email',Review::count()===$before);Auth::shouldUse('admin');
});
run('Customer currency totals',function(){
 $user=User::create(['name'=>'Multiple currencies','email'=>'multiple@example.test','status'=>'active']);foreach([['USD',40,'paid','completed'],['GBP',20,'paid','completed'],['USD',100,'pending','pending'],['USD',70,'refunded','refunded'],['USD',80,'paid','cancelled']] as [$currency,$total,$payment,$state])Order::create(['user_id'=>$user->id,'currency'=>$currency,'total'=>$total,'payment_status'=>$payment,'order_status'=>$state]);
 $controller=new App\Http\Controllers\Admin\CustomerController;$data=$controller->show($user)->getData();check('Spending preserves separate currencies and excludes unpaid/refunded/cancelled',$data['totalSpent']===['GBP'=>20.0,'USD'=>40.0]);$html=$controller->index(req(['search'=>'Multiple currencies']))->render();check('Customer currency labels accurate',str_contains($html,'GBP 20.00') && str_contains($html,'USD 40.00'));
});
run('Blog protection and media history',function(){
 $controller=new App\Http\Controllers\Admin\PostController;$data=['title'=>'Shared media article','status'=>'draft','template'=>'arizona-blog-system-test','feature_image'=>'posts/shared.png','robots_index'=>1,'robots_follow'=>1];Storage::disk('public')->put('posts/shared.png','fixture');$controller->store(req($data));$a=Post::latest('id')->first();$data['title']='Second media article';$controller->store(req($data));$b=Post::latest('id')->first();$controller->destroy($a);check('Shared article image preserved',Storage::disk('public')->exists('posts/shared.png'));
 $data['feature_image']='';$data['remove_feature_image']=1;$controller->update(req($data),$b);check('Revision media remains available',Storage::disk('public')->exists('posts/shared.png'));
 $data['status']='scheduled';$data['scheduled_at']=now()->addDay();$data['template']='missing-article-blade';check('Scheduling requires custom article file',validationBlocked(fn()=>$controller->store(req($data))));$data['status']='draft';$controller->store(req($data));check('Draft allowed before custom file creation',Post::latest('id')->first()->isDraft());
 $revision=App\Models\PostRevision::where('post_id',$b->id)->first();$revision->update(['snapshot'=>['bad'=>'snapshot']]);$title=$b->fresh()->title;$controller->restoreRevision($b,$revision);check('Invalid revision cannot modify saved article',$b->fresh()->title===$title);
});
run('Allowed module permissions',function()use($app,$admin){foreach(['admin.customers.index'=>'customers.manage','admin.reviews.index'=>'reviews.manage','admin.posts.index'=>'content.manage','admin.categories.index'=>'content.manage'] as $name=>$permission){$mock=Mockery::mock(App\Models\Admin::class)->makePartial();$mock->shouldReceive('isActive')->andReturn(true);$mock->shouldReceive('hasAdminPermission')->with($permission)->andReturn(true);Auth::guard('admin')->setUser($mock);$r=req();$r->setRouteResolver(fn()=>$app['router']->getRoutes()->getByName($name));check('Authorized admin allowed: '.$name,(new App\Http\Middleware\AdminMiddleware)->handle($r,fn()=>response('allowed'))->getStatusCode()===200);}Auth::guard('admin')->setUser($admin);});
file_put_contents(__DIR__.'/../../customer-content-fixes/extra-checks.json',json_encode($results,JSON_PRETTY_PRINT));echo 'COMPLETED '.count($results).' extra checks: '.count(array_filter($results,fn($r)=>$r['result']==='PASS')).' PASS, '.count(array_filter($results,fn($r)=>$r['result']!=='PASS'))." failures.\n";
