@extends('admin.layouts.app')
@section('title','Email Templates')
@section('page-heading','Email Templates')
@section('content')
<div class="email-page"><header class="email-hero"><div><span>Store communication</span><h2>Email Template Manager</h2><p>Edit automated subjects and messages without changing application code.</p></div><div class="hero-status"><i class="fa-solid fa-envelope-circle-check"></i><strong>{{ $templates->where('is_enabled',true)->count() }}</strong><small>active templates</small></div></header>
<section class="template-grid">@foreach($templates as $template)<article class="template-card"><div class="template-icon"><i class="fa-solid {{ $template->slug==='inventory-alert'?'fa-boxes-stacked':($template->slug==='admin-new-order'?'fa-bell':'fa-receipt') }}"></i></div><div class="template-content"><div class="template-title"><h3>{{ $template->name }}</h3><span class="{{ $template->is_enabled?'enabled':'disabled' }}">{{ $template->is_enabled?'Active':'Disabled' }}</span></div><p>{{ $template->description }}</p><dl><div><dt>Subject</dt><dd>{{ $template->subject }}</dd></div><div><dt>Variables</dt><dd>{{ count($template->available_variables ?? []) }} available</dd></div><div><dt>Last updated</dt><dd>{{ $template->updated_at?->diffForHumans() }}</dd></div></dl><div class="card-actions"><a href="{{ route('admin.email-templates.edit',$template) }}"><i class="fa-solid fa-pen"></i> Edit template</a><a class="preview" href="{{ route('admin.email-templates.preview',$template) }}" target="_blank"><i class="fa-regular fa-eye"></i> Preview</a></div></div></article>@endforeach</section>
<section class="email-help"><i class="fa-solid fa-circle-info"></i><div><h3>How variables work</h3><p>Place variables such as <code>@{{order_number}}</code> in a subject or body. They are replaced with real information when the email is sent. Only variables shown on each edit screen are accepted.</p></div></section></div>
@endsection
@push('page-styles')<style>
.email-page{display:grid;gap:19px;color:#172033}.email-hero{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:28px;border-radius:20px;background:linear-gradient(135deg,#172033,#7c3aed);color:#fff}.email-hero>div>span{color:#ddd6fe;font-size:10px;font-weight:850;letter-spacing:.14em;text-transform:uppercase}.email-hero h2{margin:6px 0 0;font-size:30px}.email-hero p{margin:7px 0 0;color:#ede9fe}.hero-status{display:grid!important;grid-template-columns:auto auto;align-items:center;gap:2px 9px;padding:12px 15px;border-radius:12px;background:rgba(255,255,255,.12)}.hero-status i{grid-row:1/3;font-size:24px}.hero-status strong{font-size:20px}.hero-status small{color:#ddd6fe}.template-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.template-card{display:grid;grid-template-columns:45px 1fr;gap:13px;padding:18px;border:1px solid #e2e8f0;border-radius:16px;background:#fff}.template-icon{display:grid;width:43px;height:43px;place-items:center;border-radius:11px;background:#ede9fe;color:#6d28d9}.template-title{display:flex;align-items:flex-start;justify-content:space-between;gap:8px}.template-title h3{margin:0;font-size:15px}.template-title span{padding:4px 7px;border-radius:999px;font-size:8px;font-weight:900;text-transform:uppercase}.template-title .enabled{background:#d1fae5;color:#047857}.template-title .disabled{background:#f1f5f9;color:#64748b}.template-content>p{min-height:38px;margin:7px 0 13px;color:#64748b;font-size:11px;line-height:1.55}.template-content dl{margin:0}.template-content dl>div{margin-top:8px}.template-content dt{color:#94a3b8;font-size:8px;font-weight:850;text-transform:uppercase}.template-content dd{margin:2px 0 0;overflow-wrap:anywhere;font-size:10px}.card-actions{display:flex;gap:7px;margin-top:15px}.card-actions a{padding:8px 9px;border-radius:8px;background:#7c3aed;color:#fff;font-size:10px;font-weight:800;text-decoration:none}.card-actions a.preview{background:#f1f5f9;color:#475569}.email-help{display:flex;gap:12px;padding:17px;border:1px solid #bae6fd;border-radius:14px;background:#f0f9ff;color:#075985}.email-help h3{margin:0;font-size:14px}.email-help p{margin:5px 0 0;font-size:11px;line-height:1.6}.email-help code{padding:2px 5px;border-radius:4px;background:#e0f2fe}@media(max-width:1100px){.template-grid{grid-template-columns:1fr 1fr}}@media(max-width:700px){.email-hero{align-items:stretch;flex-direction:column}.template-grid{grid-template-columns:1fr}}
</style>@endpush
