@extends('admin.layouts.app')
@section('title','CMS Pages')
@section('page-heading','CMS Pages')
@section('content')
<div class="cms-page"><header class="cms-hero"><div><span>Website content</span><h2>CMS Pages</h2><p>Create reusable public pages such as shipping, returns, sizing, FAQs and store policies.</p></div><a href="{{ route('admin.pages.create') }}"><i class="fa-solid fa-plus"></i> New page</a></header>
<section class="cms-stats"><article><small>All pages</small><strong>{{ $stats['all'] }}</strong></article><article><small>Published</small><strong>{{ $stats['published'] }}</strong></article><article><small>Drafts</small><strong>{{ $stats['draft'] }}</strong></article></section>
<section class="cms-panel"><form method="GET" class="cms-filter"><input name="search" value="{{ request('search') }}" placeholder="Search title or slug"><select name="status"><option value="">All statuses</option><option value="published" @selected(request('status')==='published')>Published</option><option value="draft" @selected(request('status')==='draft')>Draft</option></select><button><i class="fa-solid fa-filter"></i> Filter</button><a href="{{ route('admin.pages.index') }}">Reset</a></form></section>
<section class="cms-panel"><div class="table-wrap"><table><thead><tr><th>Page</th><th>Status</th><th>Source</th><th>Last editor</th><th>Updated</th><th></th></tr></thead><tbody>@forelse($pages as $page)<tr><td><strong>{{ $page->title }}</strong><small>/page/{{ $page->slug }}</small></td><td><span class="status {{ $page->status }}">{{ ucfirst($page->status) }}</span></td><td><strong>{{ $page->render_mode==='custom'?'Custom Blade':'Dashboard Editor' }}</strong><small>{{ $page->render_mode==='custom'?($page->blade_template.'.blade.php'):ucfirst($page->template) }}</small></td><td>{{ $page->editor?->name ?? 'Unknown' }}</td><td><strong>{{ $page->updated_at?->format('d M Y') }}</strong><small>{{ $page->updated_at?->diffForHumans() }}</small></td><td><div class="actions">@if($page->status==='published')<a href="{{ $page->public_url }}" target="_blank" title="View"><i class="fa-regular fa-eye"></i></a>@endif<a href="{{ route('admin.pages.edit',$page) }}" title="Edit"><i class="fa-solid fa-pen"></i></a><form method="POST" action="{{ route('admin.pages.destroy',$page) }}" onsubmit="return confirm('Delete this CMS page permanently?')">@csrf @method('DELETE')<button title="Delete"><i class="fa-regular fa-trash-can"></i></button></form></div></td></tr>@empty<tr><td colspan="6" class="empty"><i class="fa-regular fa-file-lines"></i><h3>No CMS pages found</h3><p>Create your first reusable website page.</p></td></tr>@endforelse</tbody></table></div>@if($pages->hasPages())<div class="pagination">{{ $pages->links() }}</div>@endif</section></div>
@endsection
@push('page-styles')<style>
.cms-page{display:grid;gap:18px;color:#172033}.cms-hero{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:27px;border-radius:20px;background:linear-gradient(135deg,#172033,#0f766e);color:#fff}.cms-hero span{color:#99f6e4;font-size:10px;font-weight:850;letter-spacing:.14em;text-transform:uppercase}.cms-hero h2{margin:6px 0 0;font-size:30px}.cms-hero p{margin:7px 0 0;color:#ccfbf1}.cms-hero>a{padding:11px 14px;border-radius:9px;background:#fff;color:#0f766e;font-weight:850;text-decoration:none}.cms-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:13px}.cms-stats article{padding:16px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.cms-stats small,.cms-stats strong{display:block}.cms-stats small{color:#64748b}.cms-stats strong{margin-top:5px;font-size:23px}.cms-panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:16px;background:#fff}.cms-filter{display:flex;gap:9px;padding:15px}.cms-filter input{flex:1}.cms-filter input,.cms-filter select{padding:10px;border:1px solid #cbd5e1;border-radius:8px}.cms-filter button,.cms-filter a{padding:10px 12px;border:0;border-radius:8px;background:#0f766e;color:#fff;font-weight:800;text-decoration:none}.cms-filter a{background:#f1f5f9;color:#475569}.table-wrap{overflow-x:auto}table{width:100%;min-width:800px;border-collapse:collapse}th{padding:11px 13px;background:#f8fafc;color:#64748b;font-size:9px;text-align:left;text-transform:uppercase}td{padding:13px;border-top:1px solid #edf0f5;font-size:11px}td strong,td small{display:block}td small{margin-top:3px;color:#94a3b8}.status{padding:5px 8px;border-radius:999px;font-size:9px;font-weight:900;text-transform:uppercase}.status.published{background:#d1fae5;color:#047857}.status.draft{background:#f1f5f9;color:#64748b}.actions{display:flex;gap:5px}.actions a,.actions button{display:grid;width:32px;height:32px;place-items:center;border:0;border-radius:7px;background:#ecfdf5;color:#047857;cursor:pointer}.actions button{background:#fff1f2;color:#be123c}.empty{padding:50px;text-align:center;color:#64748b}.empty i{font-size:34px}.empty h3{margin:10px 0 3px}.empty p{margin:0}.pagination{padding:15px}@media(max-width:650px){.cms-hero,.cms-filter{align-items:stretch;flex-direction:column}.cms-stats{grid-template-columns:1fr}}
</style>@endpush
