
<?php $__env->startSection('title','Menu Builder'); ?>
<?php $__env->startSection('page-heading','Menu Builder'); ?>
<?php $__env->startSection('content'); ?>
<div class="menu-page"><header class="menu-hero"><div><span>Website navigation</span><h2>Header & Footer Menu Builder</h2><p>Add CMS pages, existing website routes or custom links, then arrange their display order.</p></div></header>
<?php $__currentLoopData = $menus; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $menu): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
<section class="menu-panel" data-menu-panel><div class="panel-heading"><div><h3><?php echo e($menu->name); ?></h3><p><?php echo e(ucfirst($menu->location)); ?> location Â· <?php echo e($menu->items->count()); ?> item(s)</p></div><form method="POST" action="<?php echo e(route('admin.navigation-menus.reorder',$menu)); ?>" data-reorder-form><?php echo csrf_field(); ?> <?php echo method_field('PUT'); ?><div data-order-inputs></div><button><i class="fa-solid fa-arrow-down-wide-short"></i> Save order</button></form></div>
<?php if($menu->location==='mega_categories'): ?>
<div class="builder-grid"><div class="items-list" data-sort-list>
<?php $__empty_1 = true; $__currentLoopData = $menu->items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
<?php ($selectedCategory=$productCategories->firstWhere('id',(int)substr((string)$item->route_name,20))); ?>
<article class="menu-item-card" data-item-id="<?php echo e($item->id); ?>"><div class="move-buttons"><button type="button" data-move="up" aria-label="Move up">↑</button><button type="button" data-move="down" aria-label="Move down">↓</button></div><div><?php echo e($selectedCategory?->title ?? 'Deleted category — remove this link'); ?></div><form method="POST" action="<?php echo e(route('admin.navigation-menus.items.destroy',$item)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="delete-item" aria-label="Remove category">×</button></form></article>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p>Select categories to display in the mega menu.</p><?php endif; ?>
</div><aside class="add-item"><h3>Add product category</h3><p>Maximum 15 categories. Three per row on desktop. Use the arrows and Save order to arrange them.</p><form method="POST" action="<?php echo e(route('admin.navigation-menus.items.store',$menu)); ?>"><?php echo csrf_field(); ?><label>Product category<select name="category_id" required><option value="">Choose category</option><?php $__currentLoopData = $productCategories; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $category): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($category->id); ?>"><?php echo e($category->title); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label><button <?php if($menu->items->count()>=15): echo 'disabled'; endif; ?>>Add category</button></form></aside></div></section>
<?php else: ?>
<div class="builder-grid"><div class="items-list" data-sort-list>
<?php $__empty_1 = true; $__currentLoopData = $menu->items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><article class="menu-item-card" data-item-id="<?php echo e($item->id); ?>"><div class="move-buttons"><button type="button" data-move="up" aria-label="Move up"><i class="fa-solid fa-chevron-up"></i></button><button type="button" data-move="down" aria-label="Move down"><i class="fa-solid fa-chevron-down"></i></button></div><form method="POST" action="<?php echo e(route('admin.navigation-menus.items.update',$item)); ?>" class="item-edit-form"><?php echo csrf_field(); ?> <?php echo method_field('PUT'); ?>
<input name="label" value="<?php echo e($item->label); ?>" required maxlength="100"><select name="link_type" data-link-type><option value="page" <?php if($item->link_type==='page'): echo 'selected'; endif; ?>>CMS page</option><option value="route" <?php if($item->link_type==='route'): echo 'selected'; endif; ?>>Website route</option><option value="custom" <?php if($item->link_type==='custom'): echo 'selected'; endif; ?>>Custom URL</option></select>
<select name="page_id" data-type-field="page"><option value="">Choose page</option><?php $__currentLoopData = $pages; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $page): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($page->id); ?>" <?php if($item->page_id===$page->id): echo 'selected'; endif; ?>><?php echo e($page->title); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select><select name="route_name" data-type-field="route"><option value="">Choose route</option><?php $__currentLoopData = $routes; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $name=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($name); ?>" <?php if($item->route_name===$name): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select><input name="url" value="<?php echo e($item->url); ?>" data-type-field="custom" placeholder="/sale or https://example.com">
<label class="check"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" <?php if($item->is_active): echo 'checked'; endif; ?>> Visible</label><label class="check"><input type="hidden" name="open_in_new_tab" value="0"><input type="checkbox" name="open_in_new_tab" value="1" <?php if($item->open_in_new_tab): echo 'checked'; endif; ?>> New tab</label><button class="save-item"><i class="fa-solid fa-check"></i></button></form><form method="POST" action="<?php echo e(route('admin.navigation-menus.items.destroy',$item)); ?>" onsubmit="return confirm('Remove this menu item?')"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="delete-item"><i class="fa-regular fa-trash-can"></i></button></form></article>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="empty-menu"><i class="fa-solid fa-link"></i><p>No links added yet.</p></div><?php endif; ?>
</div>
<aside class="add-item"><h3>Add menu item</h3><form method="POST" action="<?php echo e(route('admin.navigation-menus.items.store',$menu)); ?>" data-menu-item-form><?php echo csrf_field(); ?><label>Link label<input name="label" required maxlength="100" placeholder="Shipping Policy"></label><label>Link type<select name="link_type" data-link-type><option value="page">CMS page</option><option value="route">Website route</option><option value="custom">Custom URL</option></select></label><label data-type-field="page">Published page<select name="page_id"><option value="">Choose page</option><?php $__currentLoopData = $pages; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $page): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($page->id); ?>"><?php echo e($page->title); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label><label data-type-field="route">Website route<select name="route_name"><option value="">Choose route</option><?php $__currentLoopData = $routes; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $name=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($name); ?>"><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label><label data-type-field="custom">Custom URL<input name="url" placeholder="/sale or https://example.com"></label><label class="check"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" checked> Visible</label><label class="check"><input type="hidden" name="open_in_new_tab" value="0"><input type="checkbox" name="open_in_new_tab" value="1"> Open in new tab</label><button><i class="fa-solid fa-plus"></i> Add link</button></form></aside></div></section>
<?php endif; ?>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>
<?php $__env->stopSection(); ?>
<?php $__env->startPush('page-styles'); ?><style>
.menu-page{display:grid;gap:18px;color:#172033}.menu-hero{padding:27px;border-radius:20px;background:linear-gradient(135deg,#172033,#7c3aed);color:#fff}.menu-hero span{color:#ddd6fe;font-size:10px;font-weight:850;letter-spacing:.14em;text-transform:uppercase}.menu-hero h2{margin:6px 0 0;font-size:30px}.menu-hero p{margin:7px 0 0;color:#ede9fe}.menu-panel{overflow:hidden;border:1px solid #e2e8f0;border-radius:16px;background:#fff}.panel-heading{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:17px 19px;border-bottom:1px solid #e2e8f0}.panel-heading h3{margin:0}.panel-heading p{margin:4px 0 0;color:#64748b;font-size:11px}.panel-heading button,.add-item form>button{padding:9px 11px;border:0;border-radius:8px;background:#7c3aed;color:#fff;font-weight:800;cursor:pointer}.builder-grid{display:grid;grid-template-columns:minmax(0,1.7fr) minmax(280px,.7fr);align-items:start}.items-list{display:grid;gap:9px;padding:17px;border-right:1px solid #e2e8f0}.menu-item-card{display:grid;grid-template-columns:27px 1fr 32px;align-items:center;gap:8px;padding:10px;border:1px solid #e2e8f0;border-radius:11px;background:#fff}.move-buttons{display:grid;gap:3px}.move-buttons button,.save-item,.delete-item{display:grid;width:27px;height:27px;place-items:center;border:0;border-radius:6px;background:#f1f5f9;color:#64748b;cursor:pointer}.item-edit-form{display:grid;grid-template-columns:1.2fr .8fr 1.3fr auto auto 30px;align-items:center;gap:6px}.item-edit-form input,.item-edit-form select,.add-item input,.add-item select{width:100%;box-sizing:border-box;padding:8px;border:1px solid #cbd5e1;border-radius:7px;font:inherit;font-size:10px}.check{display:flex!important;align-items:center;gap:4px;white-space:nowrap;font-size:9px!important}.check input{width:auto!important}.save-item{background:#dcfce7;color:#15803d}.delete-item{background:#fff1f2;color:#be123c}.add-item{padding:18px}.add-item h3{margin:0 0 13px}.add-item form{display:grid;gap:11px}.add-item label{font-size:10px;font-weight:800}.add-item label input,.add-item label select{margin-top:5px}.empty-menu{padding:40px;text-align:center;color:#94a3b8}.empty-menu i{font-size:28px}.empty-menu p{margin:8px 0 0}@media(max-width:1100px){.builder-grid{grid-template-columns:1fr}.items-list{border-right:0;border-bottom:1px solid #e2e8f0}.item-edit-form{grid-template-columns:repeat(3,1fr)}}@media(max-width:700px){.panel-heading{align-items:stretch;flex-direction:column}.item-edit-form{grid-template-columns:1fr}.menu-item-card{align-items:start}.panel-heading button{width:100%}}
</style><?php $__env->stopPush(); ?>
<?php $__env->startPush('page-scripts'); ?><script>
document.querySelectorAll('[data-link-type]').forEach(function(select){function update(){const form=select.closest('form');form.querySelectorAll('[data-type-field]').forEach(function(field){const active=field.dataset.typeField===select.value;field.hidden=!active;const input=field.matches('input,select')?field:field.querySelector('input,select');if(input)input.required=active;});}select.addEventListener('change',update);update();});
document.querySelectorAll('[data-menu-panel]').forEach(function(panel){const list=panel.querySelector('[data-sort-list]');panel.querySelectorAll('[data-move]').forEach(function(button){button.addEventListener('click',function(){const item=button.closest('[data-item-id]');if(button.dataset.move==='up'&&item.previousElementSibling)item.parentNode.insertBefore(item,item.previousElementSibling);if(button.dataset.move==='down'&&item.nextElementSibling)item.parentNode.insertBefore(item.nextElementSibling,item);});});panel.querySelector('[data-reorder-form]').addEventListener('submit',function(){const holder=this.querySelector('[data-order-inputs]');holder.innerHTML='';list.querySelectorAll('[data-item-id]').forEach(function(item){const input=document.createElement('input');input.type='hidden';input.name='items[]';input.value=item.dataset.itemId;holder.appendChild(input);});});});
</script><?php $__env->stopPush(); ?>

<?php echo $__env->make('admin.layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\ArizonaOutfits\resources\views/admin/navigation-menus/index.blade.php ENDPATH**/ ?>