<?php ($editing=$page->exists); ?>
<form method="POST" action="<?php echo e($editing?route('admin.pages.update',$page):route('admin.pages.store')); ?>" class="page-form"><?php echo csrf_field(); ?> <?php if($editing): ?><?php echo method_field('PUT'); ?><?php endif; ?>
<div class="form-grid">
<label class="wide">Page title<input name="title" value="<?php echo e(old('title',$page->title)); ?>" required maxlength="255" placeholder="Shipping Policy"></label>
<label>URL slug<input name="slug" value="<?php echo e(old('slug',$page->slug)); ?>" maxlength="255" placeholder="Generated from title"></label>
<label>Status<select name="status" required><option value="draft" <?php if(old('status',$page->status?:'draft')==='draft'): echo 'selected'; endif; ?>>Draft</option><option value="published" <?php if(old('status',$page->status)==='published'): echo 'selected'; endif; ?>>Published</option></select></label>
<label>Page source<select name="render_mode" id="pageRenderMode" required><option value="editor" <?php if(old('render_mode',$page->render_mode?:'editor')==='editor'): echo 'selected'; endif; ?>>Dashboard editor</option><option value="custom" <?php if(old('render_mode',$page->render_mode)==='custom'): echo 'selected'; endif; ?>>Custom Blade file</option></select></label>
<label data-editor-field>Page width<select name="template" required><option value="default" <?php if(old('template',$page->template?:'default')==='default'): echo 'selected'; endif; ?>>Default</option><option value="wide" <?php if(old('template',$page->template)==='wide'): echo 'selected'; endif; ?>>Wide</option><option value="minimal" <?php if(old('template',$page->template)==='minimal'): echo 'selected'; endif; ?>>Minimal</option></select></label>
<label data-custom-field>Custom Blade template<select name="blade_template" id="bladeTemplate"><option value="">Choose a file</option><?php $__currentLoopData = $customTemplates; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if(old('blade_template',$page->blade_template)===$value): echo 'selected'; endif; ?>><?php echo e($label); ?> — <?php echo e($value); ?>.blade.php</option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select><?php if(empty($customTemplates)): ?><small class="template-warning">No files found in resources/views/pages/custom.</small><?php endif; ?></label>
<label class="full">Short excerpt<textarea name="excerpt" rows="3" maxlength="1000" placeholder="Optional summary shown beneath the page title"><?php echo e(old('excerpt',$page->excerpt)); ?></textarea></label>
<label class="full" data-editor-field>Page content <small>Safe HTML tags are supported.</small><textarea name="content" id="pageContent" rows="20" maxlength="200000" placeholder="<h2>Section heading</h2><p>Your page content...</p>"><?php echo e(old('content',$page->content)); ?></textarea></label>
<div class="full custom-help" data-custom-field><i class="fa-solid fa-code"></i><div><strong>Rendered from a Laravel Blade file</strong><p>Create or edit <code>resources/views/pages/custom/your-template.blade.php</code>. The file receives the <code>$page</code> model.</p></div></div>
</div>
<section class="seo-box"><h3>Search engine details</h3><div class="form-grid"><label>Meta title<input name="meta_title" value="<?php echo e(old('meta_title',$page->meta_title)); ?>" maxlength="255"></label><label>Meta description<textarea name="meta_description" rows="3" maxlength="500"><?php echo e(old('meta_description',$page->meta_description)); ?></textarea></label></div></section>
<div class="form-actions"><button type="submit"><i class="fa-solid fa-floppy-disk"></i> <?php echo e($editing?'Save changes':'Create page'); ?></button><a href="<?php echo e(route('admin.pages.index')); ?>">Cancel</a><?php if($editing&&$page->status==='published'): ?><a class="view" href="<?php echo e($page->public_url); ?>" target="_blank"><i class="fa-regular fa-eye"></i> View page</a><?php endif; ?></div></form>
<?php $__env->startPush('page-styles'); ?><style>
.page-editor{display:grid;gap:17px;color:#172033}.editor-heading{padding:22px;border:1px solid #e2e8f0;border-radius:16px;background:#fff}.editor-heading a{color:#0f766e;font-size:10px;font-weight:850;text-decoration:none}.editor-heading h2{margin:8px 0 0}.editor-heading p{margin:5px 0 0;color:#64748b}.page-form{overflow:hidden;border:1px solid #e2e8f0;border-radius:16px;background:#fff}.form-grid{display:grid;grid-template-columns:2fr 1fr 1fr;gap:14px;padding:19px}.form-grid label{font-size:11px;font-weight:800}.form-grid .wide{grid-column:span 2}.form-grid .full{grid-column:1/-1}.form-grid label small{color:#94a3b8;font-weight:500}.form-grid input,.form-grid select,.form-grid textarea{width:100%;box-sizing:border-box;margin-top:7px;padding:10px;border:1px solid #cbd5e1;border-radius:9px;font:inherit}.form-grid textarea[name=content]{font-family:Consolas,monospace;font-size:12px;line-height:1.6;resize:vertical}.seo-box{border-top:1px solid #e2e8f0}.seo-box h3{margin:0;padding:16px 19px 0;font-size:15px}.seo-box .form-grid{grid-template-columns:1fr 1fr}.form-actions{display:flex;gap:8px;justify-content:flex-end;padding:17px 19px;border-top:1px solid #e2e8f0;background:#f8fafc}.form-actions button,.form-actions a{padding:10px 13px;border:0;border-radius:8px;background:#0f766e;color:#fff;font-weight:850;text-decoration:none;cursor:pointer}.form-actions a{background:#e2e8f0;color:#475569}.form-actions a.view{margin-right:auto;background:#ccfbf1;color:#0f766e}.template-warning{display:block;margin-top:6px;color:#b45309}.custom-help{display:flex;gap:11px;padding:14px;border-radius:10px;background:#eff6ff;color:#1e40af}.custom-help p{margin:4px 0 0;font-size:11px;line-height:1.6}.custom-help code{padding:2px 4px;border-radius:4px;background:#dbeafe}@media(max-width:750px){.form-grid,.seo-box .form-grid{grid-template-columns:1fr}.form-grid .wide,.form-grid .full{grid-column:auto}.form-actions{flex-direction:column}.form-actions>*{text-align:center}.form-actions a.view{margin-right:0;order:-1}}
</style><?php $__env->stopPush(); ?>
<?php $__env->startPush('page-scripts'); ?><script>document.addEventListener('DOMContentLoaded',function(){const mode=document.getElementById('pageRenderMode'),content=document.getElementById('pageContent'),blade=document.getElementById('bladeTemplate');function update(){const custom=mode.value==='custom';document.querySelectorAll('[data-editor-field]').forEach(el=>el.hidden=custom);document.querySelectorAll('[data-custom-field]').forEach(el=>el.hidden=!custom);content.required=!custom;blade.required=custom;}mode.addEventListener('change',update);update();});</script><?php $__env->stopPush(); ?>
<?php /**PATH C:\xampp\htdocs\ArizonaOutfits\complete-project-audit\_checks/../../resources/views\admin\pages\_form.blade.php ENDPATH**/ ?>