<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $delivery->subject }}</title>
</head>

<body style="margin:0;background:#f3f4f6;color:#1f2937;font-family:Arial,sans-serif;">

    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f3f4f6;padding:28px 12px;">
        <tr>
            <td align="center">

                <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:680px;background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 12px 35px rgba(15,23,42,.08);">
                    <tr>
                        <td style="padding:26px 30px;background:#111827;color:#ffffff;">
                            <div style="font-size:12px;letter-spacing:.12em;text-transform:uppercase;color:#c7d2fe;">
                                {{ config('app.name') }}
                            </div>

                            <h1 style="margin:7px 0 0;font-size:25px;">
                                Purchase Order {{ $purchaseOrder->reference }}
                            </h1>
                        </td>
                    </tr>

                    <tr>
                        <td style="padding:30px;">
                            <p style="margin:0 0 18px;line-height:1.7;">
                                Hello {{ $purchaseOrder->supplier->company_name ?? 'Supplier' }},
                            </p>

                            @if ($delivery->message)
                            <div style="margin-bottom:22px;padding:16px 18px;border-left:4px solid #4f46e5;background:#eef2ff;line-height:1.7;white-space:pre-line;">
                                {{ $delivery->message }}
                            </div>
                            @else
                            <p style="margin:0 0 22px;line-height:1.7;">
                                Please find the purchase-order information below. Contact us if any item, quantity, price or delivery date needs clarification.
                            </p>
                            @endif

                            <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin-bottom:24px;border:1px solid #e5e7eb;border-radius:12px;overflow:hidden;">
                                <tr>
                                    <td style="padding:12px 15px;background:#f9fafb;color:#6b7280;font-size:12px;">Reference</td>
                                    <td align="right" style="padding:12px 15px;background:#f9fafb;font-weight:700;">{{ $purchaseOrder->reference }}</td>
                                </tr>
                                <tr>
                                    <td style="padding:12px 15px;border-top:1px solid #e5e7eb;color:#6b7280;font-size:12px;">Order date</td>
                                    <td align="right" style="padding:12px 15px;border-top:1px solid #e5e7eb;font-weight:700;">{{ optional($purchaseOrder->order_date)->format('d M Y') ?: optional($purchaseOrder->created_at)->format('d M Y') }}</td>
                                </tr>
                                <tr>
                                    <td style="padding:12px 15px;border-top:1px solid #e5e7eb;color:#6b7280;font-size:12px;">Expected date</td>
                                    <td align="right" style="padding:12px 15px;border-top:1px solid #e5e7eb;font-weight:700;">{{ optional($purchaseOrder->expected_date)->format('d M Y') ?: 'To be confirmed' }}</td>
                                </tr>
                                <tr>
                                    <td style="padding:12px 15px;border-top:1px solid #e5e7eb;color:#6b7280;font-size:12px;">Total</td>
                                    <td align="right" style="padding:12px 15px;border-top:1px solid #e5e7eb;font-size:18px;font-weight:800;">£{{ number_format((float) $purchaseOrder->total_amount, 2) }}</td>
                                </tr>
                            </table>

                            @if ($delivery->attach_pdf)
                            <p style="margin:0;padding:14px 16px;border-radius:10px;background:#ecfdf5;color:#047857;font-size:13px;line-height:1.6;">
                                A PDF copy of this purchase order is attached to this email.
                            </p>
                            @endif
                        </td>
                    </tr>

                    <tr>
                        <td style="padding:18px 30px;background:#f9fafb;color:#6b7280;font-size:12px;line-height:1.6;">
                            This email was generated by {{ config('app.name') }} procurement management.
                        </td>
                    </tr>
                </table>

            </td>
        </tr>
    </table>

</body>

</html>
