<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
    >

    <title>{{ $alert->alert_title }}</title>
</head>

<body style="
    margin:0;
    padding:0;
    background:#f4f6f9;
    font-family:Arial,Helvetica,sans-serif;
">

<table
    width="100%"
    cellpadding="0"
    cellspacing="0"
    border="0"
    style="background:#f4f6f9;padding:40px 20px;"
>

<tr>

<td align="center">

<table
    width="650"
    cellpadding="0"
    cellspacing="0"
    border="0"
    style="
        background:#ffffff;
        border-radius:10px;
        overflow:hidden;
    "
>

<tr>

<td
    style="
        background:
        {{ $alert->isOutOfStock() ? '#d32f2f' : '#f57c00' }};
        color:#ffffff;
        padding:25px;
    "
>

<h1 style="margin:0;font-size:26px;">
{{ $alert->alert_title }}
</h1>

</td>

</tr>

<tr>

<td style="padding:35px;">

<p
style="
margin-top:0;
font-size:16px;
line-height:28px;
">

Hello Administrator,

</p>

<p
style="
font-size:15px;
line-height:28px;
color:#555;
">

The inventory monitoring system has detected a product that requires your attention.

</p>

<table
width="100%"
cellpadding="12"
cellspacing="0"
border="1"
style="
border-collapse:collapse;
border-color:#e5e7eb;
margin-top:30px;
"
>

<tr>

<td width="35%">
<strong>Product</strong>
</td>

<td>

{{ $alert->item_name }}

</td>

</tr>

<tr>

<td>
<strong>SKU</strong>
</td>

<td>

{{

$alert->variant?->sku
??

$alert->product?->sku
??

'Not Available'

}}

</td>

</tr>

<tr>

<td>
<strong>Current Stock</strong>
</td>

<td>

{{ $alert->stock_level }}

</td>

</tr>

<tr>

<td>
<strong>Threshold</strong>
</td>

<td>

{{ $alert->threshold }}

</td>

</tr>

<tr>

<td>
<strong>Status</strong>
</td>

<td>

{{ strtoupper(str_replace('_',' ',$alert->alert_type)) }}

</td>

</tr>

<tr>

<td>
<strong>Created</strong>
</td>

<td>

{{

$alert->created_at
?->format('d M Y h:i A')

}}

</td>

</tr>

</table>

@if($alert->isOutOfStock())

<div
style="
margin-top:35px;
background:#fdecea;
border-left:5px solid #d32f2f;
padding:18px;
font-size:15px;
line-height:28px;
color:#b71c1c;
"
>

<strong>

This product is now OUT OF STOCK.

</strong>

<br><br>

Customers will not be able to purchase this item once inventory validation is reached.

Please replenish inventory as soon as possible.

</div>

@else

<div
style="
margin-top:35px;
background:#fff8e1;
border-left:5px solid #f57c00;
padding:18px;
font-size:15px;
line-height:28px;
color:#7c4d00;
"
>

<strong>

Low stock warning.

</strong>

<br><br>

Inventory has reached the configured threshold.

Consider replenishing this product before it becomes unavailable.

</div>

@endif

</td>

</tr>

<tr>

<td
style="
background:#fafafa;
padding:20px;
font-size:13px;
text-align:center;
color:#777;
"
>

This email was automatically generated by

<strong>

{{ config('app.name') }}

</strong>

Inventory Monitoring System.

</td>

</tr>

</table>

</td>

</tr>

</table>

</body>
</html>